### ISSUE TITLE
`require': cannot load such file -- curses (LoadError)

### ISSUE THREAD

**Issue by walles** [walles/moar#10]
@hund wrote in #5:

> Ops. I was trying out several options and it looks like I mixed up moar and most. It was moar that I couldn't use.
>
> $ ./moar-0.9.6.rb <file>
> /usr/lib64/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in \`require': cannot load such file -- curses (LoadError)
> 	from /usr/lib64/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in \`require'
> 	from ./moar-0.9.6.rb:9:in \`\<main>'
> Do you want me to create a new issue for it? :)

**Comment by walles** [comment]
@Hund, can you please try this and see if `moar` starts working for you afterwards?

```
gem install curses || sudo gem install curses
```

**Comment by Hund** [comment]
> @Hund, can you please try this and see if `moar` starts working for you afterwards?
> 
> ```
> gem install curses || sudo gem install curses
> ```

Installing the gem `curses` solved the issue for me. Thanks! :)

**Comment by walles** [comment]
Fixed in 0.9.8:
<https://github.com/walles/moar/releases/latest>
