### ISSUE TITLE
Can't copy screen data

### ISSUE THREAD

**Issue by nkh** [walles/moar#102]
can't copy screen data, which is a tad weird in a terminal. happens in konsole with or without tmux which is what I use

I know that fzf and other "new" utilities fail at this too, maybe a common library

FYI: in tmux going in copy mode allows copying, this may be useful for other user to know .

**Comment by walles** [comment]
Please check if any of the workarounds in #53 works for you.

If any do, let me know and I'll update that issue to mention Konsole as well.

**Comment by walles** [comment]
@nkh did you try any of the #53 workarounds with Konsole? Did any help?

**Comment by walles** [comment]
@nkh if this is still a problem, feel free to re-open!
