### ISSUE TITLE
FrozenError: can't modify frozen String

### ISSUE THREAD

**Issue by skilleter** [walles/moar#11]
Running on Xubuntu 18.04
Cloned git repo. 
Ran ```./moar.rb test.rb``` from the 'src' subdirectory
Tried to do a search via '/' key. Got error below on entering second character of search term:

```
FrozenError: can't modify frozen String
  /home/jms/bin/moar:93:in `enter_char'
  /home/jms/bin/moar:1004:in `handle_search_keypress'
  /home/jms/bin/moar:1116:in `run'
  /home/jms/bin/moar:1333:in `<main>'

Moar version: UNKNOWN
Ruby version: 2.5.1
Ruby platform: x86_64-linux-gnu
LANG=<en_GB.UTF-8>
```

**Comment by walles** [comment]
Thanks for reporting @skilleter, just made a new release that should fix this:
https://github.com/walles/moar/releases/tag/0.9.7
