### ISSUE TITLE
Malwarebytes Malware.AI.3714137363 detection

### ISSUE THREAD

**Issue by Kamek2600** [walles/moar#115]
I installed it with the scoop package manager on Windows 11 22h2 and the install files in scoops cache are being detected as Malware.AI.3714137363. Possible false positive? Has anyone else scanner this?
From Malwarebytes detection:
Malware.AI.3714137363, C:\USERS\KAMEK\SCOOP\CACHE\MOAR#1.11.3#HTTPS_GITHUB.COM_WALLES_MOAR_RELEASES_DOWNLOAD_V1.11.3_MOAR-V1.11.3-WINDOWS-AMD64.EXE_MOAR.EXE, No Action By User, 1000000, -580829933, 1.0.64208, 63C6FDB3F194290EDD613D13, dds, 02107804, B80DC017BC8B30D8774DD106C03C52FE, 956076C1DECBFD2C563ECBA9CA187881119A3F1C2F249A16D63AB2FDBFFDF47A

**Comment by walles** [comment]
Not running Windows I have zero possibility of troubleshooting this.

I suggest you bring this up with your anti-virus software vendor.

**Comment by Kamek2600** [comment]
Looks like a false positive.
