### ISSUE TITLE
Got error while reading a big log file

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#118]
Hello Walles,

Yesterday I upgraded the moar to the latest code and while reading a big log file after closing it I saw this message. So far observed the message only once but thought to report if you know what this is all about

````
Please post the following report at <https://github.com/walles/moar/issues>,
or e-mail it to johan.walles@gmail.com.

Version: v1.11.4
LANG   : en_US.UTF-8
TERM   : screen-256color

GOOS    : darwin
GOARCH  : amd64
Compiler: gc
NumCPU  : 12

time="2023-01-15T21:46:58.023833+05:30" level=warning msg="Events buffer full, events are being dropped"

```

**Comment by walles** [comment]
Cool, thanks for reporting!

Questions:
1. How big was the file?
2. Would you say this was on a fast or slow machine?
3. Do you remember what you were doing? Searching? Scrolling with a mouse, keyboard, trackpad? Something else? Don't know :) ?

I can increase a buffer size to get rid of this, but I would prefer to first understand how it happened.

**Comment by ciscohack** [comment]
> Cool, thanks for reporting!
> 
> Questions:
> 
> 1. How big was the file? 3 and 5 MB
> 2. Would you say this was on a fast or slow machine? Running macOS 13.1, 2019 model
> 3. Do you remember what you were doing? Searching? Scrolling with a mouse, keyboard, trackpad? Something else? Don't know :) ?  Yes I was searching some keyword and scrolling as well
> 
> I can increase a buffer size to get rid of this, but I would prefer to first understand how it happened.

**Comment by walles** [comment]
This should be benign, now silenced in <https://github.com/walles/moar/commit/ddd7aec274ef3ad783f873bb69eceeb333cb2b70>.
