### ISSUE TITLE
Reload on terminal size change.

### ISSUE THREAD

**Issue by ZaxonXP** [walles/moar#119]
I am using tiling window manager, so if I open man page using `moar` as a pager, then opening new terminal cause that some of the text gets cut on the first terminal. The only way then is to quit and open the man page again, but loosing the previous position of read manual. Is there a way to reload the content (new feature request for `moar`) or this is something to configure for the terminal (using `st`)?

Kind regards,
Piotr

**Comment by walles** [comment]
AFAIK `man` checks the terminal width when it starts, and then pipes a suitably formatted text to `moar`.

`moar` can't know that it's `man` that's piping in data, and I can't see any way to handle this.

Suggestions welcome...
