### ISSUE TITLE
[Request] Add binaries for arm-based architectures

### ISSUE THREAD

**Issue by excited-bore** [walles/moar#122]
Would love to get this to run on a pi

**Comment by walles** [comment]
What ARM arch specifically?

Some Go compatible triplets would be helpful!

**Comment by excited-bore** [comment]
`uname -a`
`Linux pie 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux`

Homebrew sadly doesn't work on a raspberry as brew only supports intel chips

**Comment by walles** [comment]
To Go that seems to be `linux/arm`.

No triplets, that was for some other toolchain...

**Comment by walles** [comment]
Tagged with Debian since if `moar` had been Debian packaged then you'd likely have had it already:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944035

**Comment by walles** [comment]
Linux ARM binary: https://github.com/walles/moar/releases/tag/v1.12.0

**Comment by walles** [comment]
Ref: #137
