### ISSUE TITLE
Can i add the AUR moar-git to the intallations instructions?

### ISSUE THREAD

**Issue by Vilianexe** [walles/moar#123]
https://aur.archlinux.org/packages/moar-git

They are build from source, so they are mostly of the time up to date

**Comment by walles** [comment]
What is the exact command line to install this package?

Is it `paru -S moar-git`?

**Comment by MaximumWoahverdrive** [comment]
> What is the exact command line to install this package?

Using paru aur helper:
`paru -S moar-git`

Using yay aur helper
`yay -S moar-git`

Without an aur helper
```
git clone https://aur.archlinux.org/moar-git.git
cd moar-git
makepkg -si
```
