### ISSUE TITLE
crash: Pressing Pause/Break key crashes on Windows Terminal

### ISSUE THREAD

**Issue by simsrw73** [walles/moar#126]
Doesn't matter which shell: pwsh or cmd, both exhibit the same behavior. But it only seems to affect Windows Terminal. Does not affect WezTerm or Alacritty.

Pressing the Break key terminates moar
![break](https://user-images.githubusercontent.com/12434447/221717216-9c957553-7f9e-4300-8e7d-f5e5da3e6610.png)
It terminates moar and leaves the terminal in a somewhat broken state: trying to scroll the buffer with mouse 
or use cursor keys just output escape sequences to the terminal.

**Comment by walles** [comment]
That panic is in `twin`'s main loop. Apparently `stdin` gets closed when you do that:

<https://github.com/walles/moar/blob/c99c2e127aa72f9a59f8478541789f98f39d5ced/twin/screen.go#L207-L210>

**Comment by walles** [comment]
@simsrw73 can you try this build and see what happens?

I don't have access to Windows so I can't test it myself.

Not sure whether this fixes the whole problem, but I think it is at least one step on the way.

[moar-v1.15.4-1-g5a33eda-windows-amd64.exe.gz](https://github.com/walles/moar/files/12479529/moar-v1.15.4-1-g5a33eda-windows-amd64.exe.gz)

**Comment by walles** [comment]
I believe this should work in 1.16.0.

If not, please comment + reopen!
