### ISSUE TITLE
Syntax highlighting in moar

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#128]
I know moar use chroma fo syntax highlight but i don't know why but if I open any .log file in moar having IP address and another thing moar does not highlight but if I open the same file in Bat a cat tool it does. shall we have auto syntax highlighter 

example:--
![image](https://user-images.githubusercontent.com/11479557/222409110-e5862c76-13f6-49dc-9562-812fd472ca13.png)

Bat a CAT :-
![image](https://user-images.githubusercontent.com/11479557/222409254-dfa24721-6118-417a-9173-cb13cb211585.png)

**Comment by walles** [comment]
I can't speak for Bat, but I was unable to find any request for this in Chroma:
https://github.com/alecthomas/chroma/issues?q=is%3Aissue+is%3Aopen+log

Maybe you should try there?

**Comment by walles** [comment]
I believe this is an upstream issue.

Feel free to reopen if you disagree.

**Comment by ciscohack** [comment]
I didn't get it. Do you mean to say the style color only works with programming files and for the rest other file types like txt and log, use the terminal color. but BAT has no such limit.. it can render color style for any file whatever I choose But yes syntax highlight will work only for programming files. I expect same with moar ... request you to add this if missing

**Comment by ciscohack** [comment]
Not asking to highlight syntax through BAT support but at least color change for file I parse in moar

**Comment by walles** [comment]
Do you have a screenshot of what you'd expect?
