### ISSUE TITLE
File location not displaying correctly

### ISSUE THREAD

**Issue by Araaha** [walles/moar#131]
Whenever you do 
`systemctl status service` 
file locations are not displayed correctly. 
![2023-03-31-17:38:22-screenshot](https://user-images.githubusercontent.com/76860315/229237668-0282c898-3e6f-4d6f-8d3b-e79da4f8b051.png)

**Comment by walles** [comment]
Seems to be ANSI hyperlinks:
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#quick-example

**Comment by Araaha** [comment]
Are there plans to support them? It would be quite nice as a large number of programs seem to make use of them.

**Comment by walles** [comment]
> Are there plans to support them? It would be quite nice as a large number of programs seem to make use of them.

Yes, I intend to add support for these.

**Comment by walles** [comment]
Fix released: https://github.com/walles/moar/releases/tag/v1.14.0
