### ISSUE TITLE
Mistranslations of file reference resulting in broken characters

### ISSUE THREAD

**Issue by excited-bore** [walles/moar#133]
![moar_bug](https://user-images.githubusercontent.com/31372378/235302801-1d1ced55-655c-4d64-ac04-7cb64be12c71.png)
moar - less
I've seen other cases, but here it *seems* to be related to referencing files from the users system

**Comment by walles** [comment]
Duplicate of this one: https://github.com/walles/moar/issues/131

**Comment by walles** [comment]
Fix released: https://github.com/walles/moar/releases/tag/v1.14.0
