### ISSUE TITLE
Converts HYPHEN in HYPHEN-MINUS

### ISSUE THREAD

**Issue by 875d** [walles/moar#142]
When I run for example `man gpg`, and I search for "-e" by typing "/-e", it finds nothing.

This is because my keyboard types "-", which is U+002D HYPHEN-MINUS, while the man page uses "‐", which is U+2010 HYPHEN.

How can I convert the HYPHEN of the manpage into the HYPHEN-MINUS that my keyboard types?

**Comment by MaximumWoahverdrive** [comment]
This behavior is expected/correct

Assuming you are currently running `man gpg | moar`
you could pipe through a sed before piping into moar and replace the characters there
`man gpg | sed $'s/\u2010/\u002d/g' | moar`

**Comment by 875d** [comment]
ok I've made a wrapper script for that

THanks

**Comment by 875d** [comment]
For future reference, here is how the wrapper script would look like:
```
sed $'s/\u2010/\u002d/g' "$@" | moar
```
