### ISSUE TITLE
error: cannot spawn sh: No such file or directory

### ISSUE THREAD

**Issue by 1268** [walles/moar#144]
If I do this, everything works fine:

~~~
> git config core.pager moar
> git tag
~~~

but if I do this, I get an error:

~~~
> git config core.pager 'moar -no-clear-on-exit'
> git tag
error: cannot spawn sh: No such file or directory
~~~

**Comment by walles** [comment]
Set `export MOAR=-no-clear-on-exit` globally, then `git config core.pager moar`.

`moar` reads config from that environment variable.

**Comment by walles** [comment]
Or even better, do both of these and don't touch `git`'s config:
* `export MOAR=-no-clear-on-exit`
* `export PAGER=moar`

That will make others use `moar` as well for their paging, not just `git`.

And it opens up for using [`riff`](https://github.com/walles/riff) as well :).

**Comment by 1268** [comment]
OK your first comment is correct, but second commit is not. second comment has no error, but it also ignores the `-no-clear-on-exit` value

**Comment by 1268** [comment]
OK yes both ideas work, thank you!

**Comment by walles** [comment]
If you ever look at git diffs in the terminal, you *really* should try `riff` to make your diffs more readable:
https://github.com/walles/riff

<img width="766" alt="riff" src="https://github.com/walles/moar/assets/158201/8ae6ed81-e68d-44d8-a1c2-f2bc740aa26a">
