### ISSUE TITLE
[Request] Support NO_COLOR env

### ISSUE THREAD

**Issue by haunt98** [walles/moar#148]
Is there any roadmap to support NO_COLOR in the future ?
You can see here https://no-color.org/

**Comment by walles** [comment]
@haunt98 how / when would you personally use this?

**Comment by haunt98** [comment]
I sometimes use NO_COLOR env in CI (Jenkins) to remove color.

But personally with my lap, I don't use much

**Comment by walles** [comment]
I don't see people using `moar` in CI.

If you or somebody else has an actual use case for this, please re-open!
