### ISSUE TITLE
moar crashed when run invalid regex pattern 

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#149]
moar experienced panic crashes whenever I ran an invalid regex pattern as shown in the screenshot. I am running the latest moar version on my macOS 13.5

<img width="744" alt="image" src="https://github.com/walles/moar/assets/11479557/874045ba-4412-434d-a3cb-22bd84e9926f">

**Comment by walles** [comment]
Which shell are you using?

**Comment by walles** [comment]
Here's the code returning that error:
https://github.com/walles/moar/blob/848958dad029cbc66d5281ec79caf3d833b7293c/twin/screen-setup.go#L60

Can't say how this could happen, but can you try to repro this with:
* A non-customized terminal app, like the built in one
* A non-customized shell, `bash`, `zsh`, `fish` or whatever, just as long as it's something you haven't customized

**Comment by ciscohack** [comment]
Here I have tried warp terminal and have the same result.


<img width="1034" alt="image" src="https://github.com/walles/moar/assets/11479557/635b620a-168f-4bd8-b547-9c7da3ebb3e8">

**Comment by walles** [comment]
I was able to repro using `ug --pager=moar '[' /dev/null`.

**Comment by ciscohack** [comment]
awesome my friend ...
