### ISSUE TITLE
panic crash with ugrep query

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#150]
While doing some log analysis and using ugrep with moar observed a panic crash like the below screenshot

<img width="1920" alt="image" src="https://github.com/walles/moar/assets/11479557/8f5f0548-9d0c-4ba1-bd79-d8e40215395b">

This is the query which I ran and observed a crash

<img width="381" alt="image" src="https://github.com/walles/moar/assets/11479557/0fdc7664-7c9c-4c2d-829e-628142841381">

between I am running latest moar and ugrep version on macOS 13.5.1

**Comment by walles** [comment]
What does `moar --version` say?

**Comment by walles** [comment]
Can you try the same thing with this release? This is a binary built for macOS AMD64 with 5a33eda7660d88e3b089875a603d8dc28198951a in it.

[moar.gz](https://github.com/walles/moar/files/12487714/moar.gz)

**Comment by ciscohack** [comment]
I have an intel model and unfortunately out for 7 days on vocation

**Comment by walles** [comment]
> I have an intel model

Then [my binary should work](https://www.quora.com/What-is-the-difference-between-x86_64-and-AMD64). Enjoy your vacation!

**Comment by walles** [comment]
Should work in v16.0.0.

I managed to repro, thanks for the instructions!
