### ISSUE TITLE
moar line number rendering query

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#151]
Hi John,

I noticed that when the number of lines in a document becomes large, underscores are used instead of normal line numbers. This causes readability issues and can be confusing at times. Is it possible to display normal line numbers instead of underscores?

the line are 1470 not 1_470

<img width="55" alt="image" src="https://github.com/walles/moar/assets/11479557/09842b70-f7ae-44ff-8ad0-e8ea93c42d51">

**Comment by ciscohack** [comment]
@walles Any comment on this request

**Comment by walles** [comment]
When line numbers become large, 100000 or so, thousands separators are invaluable for readability:
https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping

`_` is a locale neutral choice, which also happens to work in a number of programming languages.

Reading up a bit it seems like the thousands separators should be added for numbers 10000 and above, not 1000 and above as `moar` does it, and I can make that change:
* https://en.wikipedia.org/wiki/Decimal_separator#Exceptions_to_digit_grouping
* http://wordpress.mrreid.org/2014/05/27/stop-putting-commas-in-your-numbers/

**Comment by ciscohack** [comment]
@walles No is 1000 only ....if read the lines in my text its 1468,1469 so on not 1_468

**Comment by ciscohack** [comment]
thanks
