### ISSUE TITLE
moar style switch seems broken and not working

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#159]
I have tried moar --style=gruvbox and suppose that moar will render the color format in gruvbox theme but  it seems not working and moar is using default terminal theme color style for moar.. Running latest moar version on macOS sonoma 14.0 version. Ideally it should use the terminal theme style only when no --style switch option used along with moar

<img width="1006" alt="image" src="https://github.com/walles/moar/assets/11479557/bc13cd39-efbe-4d74-9da7-6a7ddbc55bdf">

**Comment by ciscohack** [comment]
one more thing this help section also seems showing the wrong switch like it showing -style but if I am correct it should be
 --style

**Comment by walles** [comment]
Works for me with `moar` `v1.17.0` in the macOS terminal.

1. Can you try this in the macOS terminal? To rule out any terminal related configuration on your side?
2. What does `echo $MOAR` say?
3. What does `echo $TERM` say?

`moar --style=gruvbox moar.go`:

<img width="458" alt="moar-gruvbox" src="https://github.com/walles/moar/assets/158201/b50ed42e-527e-499f-ab13-0cd857e982a5">

`moar moar.go`:

<img width="458" alt="moar-default-style" src="https://github.com/walles/moar/assets/158201/e757ef94-d6d1-48a6-9f60-c79cf51c2c47">

**Comment by m3tav3rse** [comment]
> one more thing this help section also seems showing the wrong switch like it showing (-style) but if I am correct it should be (--style)

Both flags are accepted and correct, `-style` is just printed by default. See [this link](https://pkg.go.dev/flag#hdr-Command_line_flag_syntax) for reference.

**Comment by ciscohack** [comment]
@walles @m3tav3rse Thanks for your comment and input. I don't know why but it's not working for me 

John here is output of value you requested

<img width="291" alt="image" src="https://github.com/walles/moar/assets/11479557/a506a34b-f0a5-4ac2-b729-aaee90a285be">

**Comment by walles** [comment]
If you have `MOAR=--style=gruvbox` and run these two commands, then both of them will use the Gruvbox theme:
* `moar --style=gruvbox moar.go`
* `moar moar.go`

1. Can you post screenshots of `moar --style=igor` vs `moar --style=gruvbox`?
2. Can you post, in a copy-pasteable format, the exact command lines you use?

**Comment by ciscohack** [comment]
here is the output of commands

moar --style=igor  asa.log
<img width="483" alt="image" src="https://github.com/walles/moar/assets/11479557/7ffa35d7-0586-4a8f-8e74-affbd26350f9">

moar --style=gruvbox asa.log
<img width="501" alt="image" src="https://github.com/walles/moar/assets/11479557/7c54b3dd-a8ea-4278-86a7-5f641ec5eb1c">

**Comment by walles** [comment]
There is no highlighting for `.log` files, so the theme doesn't matter.

Ref: <https://github.com/walles/moar/issues/128#issuecomment-1453754629>

**Comment by ciscohack** [comment]
I didn't get it. Do you mean to say the style color only works with programming files and for the rest other file types like txt and log, use the terminal color. but BAT has no such limit.. it can render color style for any file whatever I choose But yes syntax highlight will work only for programming files. I expect same with moar ... request you to add this if missing

**Comment by walles** [comment]
> [BAT] can render color style for any file whatever I choose But yes syntax highlight will work only for programming files

"Syntax highlight" is what moar provides through Chroma (I think).

But what is "color style"? And how is that different from syntax highlight?

**Comment by ciscohack** [comment]
so I thought suppose my terminal theme is Gruvbox but when I read and log file through moar then it uses Dracula color rendering so thought color style is the option to do so..BAT do this for me.

**Comment by ciscohack** [comment]
Like this example 
the terminal theme is Solarize but BAT theme is gruvbox and rendering is also like gruvbox

<img width="889" alt="image" src="https://github.com/walles/moar/assets/11479557/0c979890-7a3c-43b1-8128-1a38b21a02f8">


now here same file in moar

<img width="919" alt="image" src="https://github.com/walles/moar/assets/11479557/38dc2aaa-e438-475b-9b91-4115d4709e90">

**Comment by walles** [comment]
What command line did you use to get this?

That's a shell script, and if it's named `whatever.sh` then `moar` should highlight it.

**Comment by ciscohack** [comment]
moar .exports and bat .exports is what I used on kitty terminal . As I said I already tested all combo before raising ticket 
moar is not working as I received whereas BAT is working fine

**Comment by walles** [comment]
I experimented a bit and it seems like `bat` looks at the contents of the file to identify its MIME type, whereas `moar` just looks at the file name.

Sort of related to #134.

It might be possible to have `moar` use `DetectContentType()` as a fallback to determine the MIME type if the file name based detection fails.

This would likely fix the `.exports` highlighting, but it would not do anything for the `asa.log` highlighting that you mentioned above: <https://github.com/walles/moar/issues/159#issuecomment-1741984095>

**Comment by ciscohack** [comment]
hmm okay thanks John

**Comment by walles** [comment]
But `DetectContentType` seems pretty limited:
https://cs.opensource.google/go/go/+/refs/tags/go1.21.1:src/net/http/sniff.go;l=65-195

This one seems broader, but doesn't detect shell scripts:
https://github.com/gabriel-vasile/mimetype

Same for this one, doesn't detect shell scripts:
https://github.com/h2non/filetype

This one has native dependencies, making it impractical:
https://github.com/rakyll/magicmime

Other suggestions welcome, none of the above are usable for this out of the box unfortunately.

**Comment by walles** [comment]
This one seems nice, but requires the user to have Tensorflow installed, which I assume most people don't:
https://github.com/robherley/guesslang-go

**Comment by ciscohack** [comment]
@walles  Thanks a lot my friend for all your support and time on this. Yes, many and even I don't like 10 other dependencies installed to run 1 software. That's ok you can leave I use BAT for such needs as

**Comment by walles** [comment]
Yet another candidate that doesn't recognize shell scripts:
https://github.com/zRedShift/mimemagic

**Comment by ciscohack** [comment]
@walles it's not about shell script i feel scripts anyway moar is able to recognize

**Comment by ciscohack** [comment]
txt and log these are 2 most common type

**Comment by walles** [comment]
Neither of those have any highlighting, so even if they were detected correctly they wouldn't receive any highlighting anyway.

**Comment by ciscohack** [comment]
@walles there is highlight for log in BAT but point is not about highlight..seems you not getting the request fully I said suppose my terminal theme is solarize and want my moar to render any log in color of gruvbox

**Comment by walles** [comment]
Do you mean that the text of the log should have some certain color based on the theme (gruvbox)?

**Comment by ciscohack** [comment]
@walles just noticed the screenshot and understands the requirement. below SS my terminal theme is Solarize dark and when I ran bat <file_name.log> the color of text is a little yellowish and some numeric and hex values were highlighted

Whereas when I ran same thing in moar in second SS. You will see it used the Solarize theme colour style only for text though I have color style gruvbox chosen in moar


With gruvbox color style in BAT:--
<img width="811" alt="image" src="https://github.com/walles/moar/assets/11479557/0327ae4e-7321-4cde-8e73-84c9e8531ad1">


With gruvbox color style in moar:--

<img width="746" alt="image" src="https://github.com/walles/moar/assets/11479557/b452a235-29bc-4709-8f31-41eec84b411c">


Ideally when I choose the color style gruvbox in moar then color of text should be little yellowish as in first screenshot. Now I hope you understand the requirement

**Comment by walles** [comment]
After cbbdaf632b322eadd915ba9659f873f8213d64f1, just released with v1.18.1, this should now work on 256 color terminals as well.

**Comment by ciscohack** [comment]
@walles you said that 1.8.0 will have syntax highlights like bat to some extent for log/text files like in bat screenshot above but I don't see it ..

**Comment by walles** [comment]
Try v1.18.1.

**Comment by ciscohack** [comment]
ok waiting for release update to be available

**Comment by ciscohack** [comment]
@walles just upgraded to 1.18.1 but the result is not what asked second I don't know what changes you did but anyway thank you so much for all your hard work

**Comment by walles** [comment]
If you want real highlighting of `.log` files you have to request it here:
https://github.com/alecthomas/chroma/issues

After it's implemented there then `moar` can be upgraded.

Here's what `moar --style=gruvbox /etc/services` does with moar 1.18.1. Notice how the color of text is a little yellowish for this unknown-format file. Was that not what you asked for in <https://github.com/walles/moar/issues/159#issuecomment-1744124203>?

<img width="612" alt="Skärmavbild 2023-10-14 kl  18 47 40" src="https://github.com/walles/moar/assets/158201/00907639-0d13-4af8-a6aa-a3420da18319">

**Comment by ciscohack** [comment]
@walles now try Dracula and cappuccino-macchiato style and see what moar color is rendering

**Comment by walles** [comment]
I'll need to bump Chroma to a newer version for this, the catppuccin themes were updated in July:
https://github.com/alecthomas/chroma/pull/797

**Comment by ciscohack** [comment]
@walles Thanks, In fact for another style.. the result outcome is not that good I means only this area Moar lack a functionality compare to BAT else moar has unmatched and the best tool

**Comment by walles** [comment]
Is this closer to what you'd expect from `--style=catppuccin-macchiato`?

<img width="528" alt="Skärmavbild 2023-10-15 kl  07 53 00" src="https://github.com/walles/moar/assets/158201/f871f502-14e1-4300-9839-c768754e8b9d">

**Comment by ciscohack** [comment]
> Is this closer to what you'd expect from `--style=catppuccin-macchiato`?
> 
> <img alt="Skärmavbild 2023-10-15 kl 07 53 00" width="528" src="https://user-images.githubusercontent.com/158201/275305289-f871f502-14e1-4300-9839-c768754e8b9d.png">

yes color point of view it's now as per your SS seems matching but there is no highlight at least for some keyword like IP/Port HEX value etc. as bat is doing

**Comment by walles** [comment]
If you want log file highlighting you have to request it here:

https://github.com/alecthomas/chroma/issues

**Comment by ciscohack** [comment]
> If you want log file highlighting you have to request it here:
> 
> https://github.com/alecthomas/chroma/issues

The request is already raised but I don't know whether they will do it or not.

https://github.com/alecthomas/chroma/issues/871

**Comment by ciscohack** [comment]
@walles  is this --style=catppuccin-macchiato? issue resolved as I am still having the problem and this style showing red color

**Comment by walles** [comment]
Just released `moar v1.18.2` with that fix in it.

**Comment by ciscohack** [comment]
> Just released `moar v1.18.2` with that fix in it.

ok Thanks!
