### ISSUE TITLE
Mouse/Trackpad Scroll Support

### ISSUE THREAD

**Issue by ron-wolf** [walles/moar#16]
On macOS (Darwin), `less` allows using the mouse or trackpad to scroll up & down. However, this feature is not provided by `moar`. Do we have any insight on how this feature is implemented? Judging by the output of `symbols $(which less)`, `less` uses the POSIX terminal interface (i.e., `termios.h`), since it mentions multiple functions from [`tcsetattr(3)`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/tcsetattr.3.html). This may indicate one potential implementation path.

**Comment by walles** [comment]
I'm developing this on a Mac, and I do have scroll wheel / trackpad support.

Please try this:
1. `less /etc/passwd` with a short enough window, verify that mouse scrolling works.
2. `moar /etc/passwd` in the same window, try mouse scrolling
3. `less /etc/passwd` again, verify that mouse scrolling still works

If 1 and 3 works but not 2, then this seems to be an issue with `moar`.

What terminal are you using (I'm on `iTerm2`).

**Comment by walles** [comment]
Just released 0.9.12 which should fix this, @ron-wolf can you verify if it works for you?

**Comment by ron-wolf** [comment]
@walles Yes, it does! I do notice quite a bit more lag with `moar`, but it does indeed support mousewheel scrolling, amazing!
