### ISSUE TITLE
moar as pager showing invisible character while viewing a text file 

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#161]
Hi Johan,

I am sorry for reporting another issue where I am using ugrep to search the pattern in files while paging to moar. moar shows invisible character highlight those with colors and fills the screen with color that looks bad.. can you please fix or hide the invisible characters.

<img width="879" alt="image" src="https://github.com/walles/moar/assets/11479557/c0de02d1-9967-4fee-8764-321732f1450e">

**Comment by ciscohack** [comment]
> Hi John,
> 
> I am sorry for reporting another issue where I am using ugrep to search the pattern in files while paging to moar. moar shows invisible character highlight those with colors and fills the screen with color that looks bad.. can you please fix or hide the invisible characters.
> 
> <img alt="image" width="879" src="https://user-images.githubusercontent.com/11479557/273401232-c0de02d1-9967-4fee-8764-321732f1450e.png">

If I use BAT as pager these invisible characters not show up and ugrep match only the pattern and output looks clean

**Comment by ciscohack** [comment]
another observation if not use wrap text and scroll to the right moar fill the spaces with color which is really bad-looking output sometimes. example SS below ... this get worse with ugrep and other tools combination 

<img width="1027" alt="image" src="https://github.com/walles/moar/assets/11479557/146aca90-4099-4a11-b78c-7aa8fd955648">

**Comment by walles** [comment]
1. Have you tried with `--render-unprintable=whitespace`?
2. Please provide screenshots of the full windows. I don't understand where all that pink is coming from.

> another observation

Please open separate tickets for separate issues.

**Comment by ciscohack** [comment]
@walles thanks for the comment. this is not new issue but same issue pink coming from ugrep auto color as I used ugrep to search keywords and parse the output in moar pager. but in the second screenshot, I opened a text file without a wrap and scrolled it to right and grey color picked up by moar from theme 


should I use "--render-unprintable=whitespace?" like this moar --render-unprintable=whitespace? <file>

**Comment by walles** [comment]
Is there any way for me to reproduce this?

**Comment by ciscohack** [comment]
@walles this option "--render-unprintable=whitespace" solved invisible character issue but if I scroll to the right then empty or blank area filled with grey color

Yes you can reproduce by opening any text file and do not use wrap then scroll right to read long text and you will see the issue

**Comment by walles** [comment]
I was talking about reproducing the pink background.

Please open another ticket for the wrapping issue.

**Comment by ciscohack** [comment]
@walles pink colour issue disappeared with this option "--render-unprintable=whitespace". so now you can focus on second issue

**Comment by walles** [comment]
But I would like to know where the pink is coming from.

Do you have repro instructions?

**Comment by ciscohack** [comment]
OK, Here is the step I was running on my terminal to search traffic flow from src and dst IP and the command was

ugrep '5080.*5075' <file_name.txt> | moar

**Comment by walles** [comment]
1. What if you just `moar file_name.txt`? Without `ugrep`? Does that show anything in pink?
2. Is it possible for you to provide (some part) of the input file as well? I'm guessing the input file contents might have something to do with this.

**Comment by ciscohack** [comment]
@walles No, if I run moar file_name.txt then I don't see pink color but if I scroll to right then the empty area is filled with grey color as shared above.

There is no relation with the input file as the input file is just a plain firewall log file having src/dst IP and port details. sorry can't share the log but if you want to reproduce it. then follow below steps

-- Use kitty terminal having onedark pro theme.
-- Use the ugrep color always option and pattern as I mentioned in the above screenshot for log files having IP and port details ...hopefully, you will see the issue.

**Comment by walles** [comment]
I can repro the grey background thingy in Kitty, let me look into that.

It works in iTerm2, so I'll just have to make sure to emit ANSI escape codes that work in both.

**Comment by ciscohack** [comment]
Thanks! I see you have closed my previous ticket related to colour style issue I raised... is there any fix update coming for that? I didn't see any update but issue is marked as fixed

**Comment by walles** [comment]
That fix was released with `moar` 1.18.0 about seven hours ago now.

Tickets close when fixes are merged to master rather than on releases going out. This is confusing on my end as well...

**Comment by ciscohack** [comment]
@walles Thanks! Is this release has colour fix also?

**Comment by walles** [comment]
Scrolling right should work in Kitty with that release.

Also, using the theme color for not-highlighted files is in there, but it might need `--colors=16m` to work. Will fix that in a patch release.

**Comment by ciscohack** [comment]
Thanks a lot
