### ISSUE TITLE
[feature request] configure mouse scroll speed

### ISSUE THREAD

**Issue by postsolar** [walles/moar#168]
It would be awesome if I could speed mouse scroll up. An alternative for me would be to be able to *disable* mouse because that would make the terminal I'm using (`foot`) send fake key up/down presses at a greater speed.

**Comment by walles** [comment]
I just released 1.19 which automatically disables `moar`'s built-in mouse support in Foot.

Maybe that solves your issue?

**Comment by postsolar** [comment]
That solver it for me personally, although that option in `foot` is configurable so some users might get confused if they don't have it enabled or have disabled it themselves for some reason. Anyways, thank you for your work!

**Comment by walles** [comment]
For the record I tried this using Foot and no customization at all, so at least by default it should work.

YMMV and I totally agree that this could potentially fail for some people.
