### ISSUE TITLE
[bug] URL escapes don't get reset

### ISSUE THREAD

**Issue by postsolar** [walles/moar#169]
Terminal: `foot version: 1.16.2-8-gca46edfe (Nov 10 2023, branch 'master') +pgo +ime +graphemes -assertions`

To reproduce:
```shell
> eza --hyperlink | moar
```

Inside the app, the hyperlink highlight will be visible in the help page too and it will be present even after exiting `moar`.

<details>
<summary>Screenshots</summary>

1)
![image](https://github.com/walles/moar/assets/120750161/6f1bfb47-cf89-43b1-b506-1de9b786cae0)

2)
![image](https://github.com/walles/moar/assets/120750161/4e78805f-37fa-409f-9531-c7f7b44cbe00)

3)
![image](https://github.com/walles/moar/assets/120750161/6c75ebb3-5cc6-4fcb-8798-22f983732468)

4)
![image](https://github.com/walles/moar/assets/120750161/9b720a00-d4f7-47d8-84a8-bda19d4860d2)

</details>

**Comment by walles** [comment]
Fixed in 1.18.6. Thanks for reporting @postsolar!
