### ISSUE TITLE
Add flag for line numbering

### ISSUE THREAD

**Issue by Seirdy** [walles/moar#17]
A flag like `--numbers` could enable a column for line numbers, much like what [`bat`](https://github.com/sharkdp/bat), another colorizing pager, does.

**Comment by walles** [comment]
Just released `0.9.13`, now with line numbers.

Good thing you filed this, I've been wanting this as well, thanks for the nudge :).

And to be picky, `bat` isn't a pager, but it does use a pager. Doing `export PAGER=moar` somewhere in your shell init script should make Bat use `moar` for paging.
