### ISSUE TITLE
Go to previous search result after hitting end causes moar to freeze with 100% CPU usage

### ISSUE THREAD

**Issue by fixxi** [walles/moar#182]
Ahoi!

First of all, thank you for this handy tool and your ongoing work to make it better.

There seems to be a bug when cycling through the search results. These are the steps to reproduce it:
- `man moar | moar`
- search for an existing string (eg "pager")
- hit n until status line says "Not found: ..."
- hit p or Shift-n

I've tried it in kitty and foot with the same result.

EDIT: effects version 1.22.0, earlier versions work as expected

**Comment by walles** [comment]
Fully (hopefully) fixed by b5f9b88c31f1e8954db094f040719034881ccb23.

**Comment by walles** [comment]
Just released 1.22.1 which should work, do try it, thanks for your very clear report @fixxi!

**Comment by fixxi** [comment]
Confirmed.
