### ISSUE TITLE
moar selction option seems changed again in new release for macOS

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#185]
I did a moar upgrade today to pull the latest changes and noticed that selection option reverted back to old option key + press mouse button option.  it's not very convenient in previous 3-4 release press the mouse right button and select was working flawless. I don't know the reason for changing it back. can we get this option back.

**Comment by ciscohack** [comment]
I don't know what is the problem but sometimes it working but sometimes mouse click and select is not working

**Comment by ciscohack** [comment]
@walles  I would also like to know that the last theme was rendered by version 1.22.3 version and then you made some correction in latest 1.23 version. I liked that theme but now I am not able to pull that theme information. Based in color it was matching to ANSI color but there is no ANSI theme for moar

**Comment by walles** [comment]
Kindly open two separate tickets for these two separate problems.

**Comment by ciscohack** [comment]
> Kindly open two separate tickets for these two separate problems.

Done.. just help me to know is there way to install old version with brew install command

**Comment by walles** [comment]
Which terminal are you using for `moar`?

If multiple, please list them all.

Also, do these problems reproduce without `ct`?

**Comment by ciscohack** [comment]
Sometimes I use kitty, sometime Alacritty and sometimes Iterm2... it was working flawless without mouse mode switch but now it not working. It does not reproduce without CT. But with CT it was working in the previous version

**Comment by walles** [comment]
With Kitty and Alacritty, mouse support should Just Work (TM).

With iTerm2 you must go to `Preferences / Profiles / Default / Terminal / ` and uncheck "Report mouse clicks & drags".

**Comment by ciscohack** [comment]
@walles Kitty and Alacritty mouse click working fine without CT and mouse mode definition but with CT I have to define mouse mode in the configuration to work which is not the case earlier.. Iterm2 not tested

**Comment by walles** [comment]
> It does not reproduce without CT

Kindly bring this up with the CT developers.
