### ISSUE TITLE
latest moar breaks in iterm2

### ISSUE THREAD

**Issue by rwmitchell** [walles/moar#188]
I updated to the latest rev and moar completely borked the terminal.   After running ./moar MOUSE.md I get:

<img width="1236" alt="image" src="https://github.com/walles/moar/assets/15944841/8399039b-b649-4fb6-8e19-1ce0b16a8559">

and I get an ```execute: ``` prompt that doesn't let me do anything.

I then walked thru the various commits.  The last working commit for me is:  711960c606c922b284c110ef84f47decb0a59ef8.

commit 0ddefbdeb79cd03d47852daaa0974080326b9e40 fails with:

<img width="1232" alt="image" src="https://github.com/walles/moar/assets/15944841/86661e86-a204-43d7-a193-38d1fbde00bb">

I'm using iTerm2 Build 3.5.0beta18.

**Comment by postsolar** [comment]
I'm getting the first, but not the second error on respective commits on foot terminal.

When given one filename, `moar` panics as on the first screenshot. When given multiple filenames, it prints a normal error. When given either one or multiple filenames and piped into another program as described in https://github.com/walles/moar/commit/f4af673d3c22e8435f51ee384ae7c67168bf4d38 it works without errors.

**Comment by rwmitchell** [comment]
The latest update fixes moar from crashing, but it has lost colorization of the same file.

This is from my older version (v1.22.3-3-g305d247):

<img width="614" alt="image" src="https://github.com/walles/moar/assets/15944841/8e273586-c348-4072-9f63-90eb954f3c35">

And this from the current version (v1.23.0-3-g35b0ffc):
<img width="648" alt="image" src="https://github.com/walles/moar/assets/15944841/f51ae280-b794-41cf-bed3-f243244ed625">

both are generated from the shell, only switching between moar and ./moar
Has something else changed that requires and update of settings?

Thanks for all your work.!

**Comment by rwmitchell** [comment]
version v1.23.2 seems to fix my issues.

**Comment by walles** [comment]
> version v1.23.2 seems to fix my issues.

Thanks for confirming @rwmitchell!
