### ISSUE TITLE
Syntax highlight for Org

### ISSUE THREAD

**Issue by yaaama** [walles/moar#189]
I noticed that 'Org-mode' is not syntax highlighted when using moar.

It may be a problem with Chroma so if you think thats also the case I will send the issue over there.

**Image of issue:**
![pic-window-240117-1347-25](https://github.com/walles/moar/assets/106480928/4bbf4fee-2d01-4585-a0c8-b0cb3a50d083)

Thanks for all of your work!

:EDIT: 
Wanted to mention that I have tried it using different terminals.

**Comment by walles** [comment]
100% Chroma.

Once it's in there, open another issue for `moar` and I'll include it!
