### ISSUE TITLE
moar -no-clear-on-exit -quit-if-one-screen with file located in /tmp creates problems with kitty terminal

### ISSUE THREAD

**Issue by jwezel** [walles/moar#190]
The mentioned command generates input on the terminal as depicted in the following screenshot:

![Screenshot_20240118_172319](https://github.com/walles/moar/assets/2018220/7c2f8b82-a1e4-40d4-b73e-72c7ec191b2d)

However, the problem occurs only in kitty terminal, not xterm.

Edit: initially I thought it has to do with the fact that the file is empty, but now I realize it is the fact that the file is located in directory `/tmp`.

**Comment by walles** [comment]
What version of kitty is this?

I just tried it on Kitty 0.31.0 and I was unable to repro.

Also, please do `moar --version`.

**Comment by jwezel** [comment]
Kitty version 0.30.1
Moar version 1.23.0

**Comment by walles** [comment]
I managed to reproduce by changing this timeout to zero:

https://github.com/walles/moar/blob/d391bab3b180d451ab8f6de33665d6df2cbf3703/moar.go#L605

On my system this has never taken more than about 3ms, even on Kitty.

Bumping to 50ms.
