### ISSUE TITLE
Terminal codes displayed after using moar as a pager.

### ISSUE THREAD

**Issue by dsully** [walles/moar#191]
Hi again - there's a new issue relating to piped paging that appeared in the last few days.

Just updated to 1.23.1 and it's still there:

![CleanShot 2024-01-19 at 06 56 46@2x](https://github.com/walles/moar/assets/22371/d21c673d-4912-4822-badf-6eb7cb3e2373)

```shell
$ echo $PAGER
moar
$ echo $MOAR
-statusbar bold -no-linenumbers -no-clear-on-exit -style nord -colors 16M -wrap -quit-if-one-screen
```

**Comment by walles** [comment]
Done in c7eaf9a87904383cc9dcb19d8dc50e2c1cd33b6a.
