### ISSUE TITLE
Not getting syntax highlighting on python file in ubuntu on WSL.

### ISSUE THREAD

**Issue by pacanukeha** [walles/moar#202]
Using Ubuntu 22.04 on WSL, up-to-date.
Installed moar using `brew install moar`
moar path/to/file.py

Expected:
python syntax is highlighted

Experienced:
python syntax is displayed but not highlighted

I thought there might be some sort of conflict with oh-my-posh as a terminal line decorator but I disabled that and it made no difference.

I tried manually installing Chroma from brew and it made no difference.

**Comment by walles** [comment]
This is super weird.

Can you copy / paste the output of `moar --version` and `moar --help` here?

**Comment by walles** [comment]
Please re-open if you have more information on this @pacanukeha.

**Comment by pacanukeha** [comment]
I do not appear to have the authority to Re-Open this issue.

**Comment by walles** [comment]
What about `moar --trace path/to/file.py`?

Then just quit immediately after the (not-highlighted) file shows up.

Should print lots of debug information after you exit the pager, please post here what you get!

**Comment by pacanukeha** [comment]
here you go!  some interesting lines in there.
```
moar --trace ./get_services.py
Please post the following report at <https://github.com/walles/moar/issues>,
or e-mail it to johan.walles@gmail.com.

Version: v1.23.10
LANG   : C.UTF-8
TERM   : xterm-256color

GOOS    : linux
GOARCH  : amd64
Compiler: gc
NumCPU  : 20

time="Apr 29 14:27:33.614988" level=debug msg="Counted 10 lines in 561.19µs at 56.119µs/line"
time="Apr 29 14:27:33.616048" level=debug msg="Stream read in 822.774µs"
time="Apr 29 14:27:33.666339" level=debug msg="Terminal background color still not detected after 50.397388ms, giving up"
time="Apr 29 14:27:33.666355" level=trace msg="Pager starting"
time="Apr 29 14:27:33.669363" level=trace msg="Reader done, contents explicitly set"
time="Apr 29 14:27:33.669373" level=debug msg="onDone() took 53.308971ms"
time="Apr 29 14:27:36.235128" level=trace msg="ttyin high watermark bumped to 1 bytes"
time="Apr 29 14:27:36.235190" level=trace msg="Handling rune event '\x03'/0x0003..."
time="Apr 29 14:27:36.235198" level=debug msg="Unhandled rune keypress '\x03'/0x00000003"
time="Apr 29 14:27:39.333655" level=trace msg="ttyin high watermark bumped to 11 bytes"
time="Apr 29 14:27:39.333733" level=debug msg="Unhandled multi character mouse escape sequence(s): {<0x1b>[<0;96;22M}"
time="Apr 29 14:27:39.474395" level=debug msg="Unhandled multi character terminal escape sequence(s): {<0x1b>[<0;96;22m}"
time="Apr 29 14:27:46.600171" level=trace msg="Handling rune event 'q'/0x0071..."
time="Apr 29 14:27:46.600187" level=trace msg="Pager done"
```

**Comment by walles** [comment]
Just made a new release with the fix in it, thanks for reporting @pacanukeha!

The fixed release should show up in Homebrew within an hour or so.

https://github.com/walles/moar/releases/tag/v1.23.11

**Comment by pacanukeha** [comment]
Great, thanks!
