### ISSUE TITLE
moar pick the lighter tone of terminal theme for text rendering

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#206]
Hi Johan,

I know you and I worked a few months back where you added the ability in Moar to render text based on a terminal theme.
Now I have a Dark terminal theme with the Text Foreground colour white. But in Moar, the colour white is a lighter tone whereas if I use Moar with the ct tool, I get the correct tone fine. Could you please change the code or fix it?

Here is the sample output of text rendering in Moar without the CT tool combination.

<img width="865" alt="image" src="https://github.com/walles/moar/assets/11479557/42f95667-15bd-4dfe-9b7c-fb19b827e498">

And here is the sample with CT tool ... hope you remember this tool the last time I shared it with you. But here I am not trying to tell you to fix the CT thing but the issue of color rendering in the terminal. focus on white color rendering of 

<img width="856" alt="image" src="https://github.com/walles/moar/assets/11479557/11f630c1-0c10-4a7d-b5b9-c217715340e7">

**Comment by walles** [comment]
If you don't like the default dark theme, pick another one from here that you like better:

https://xyproto.github.io/splash/docs/longer/all.html

For example: `moar --style=base16-snazzy /etc/services`

**Comment by walles** [comment]
Did this resolve your coloring issue? Can this be closed?

**Comment by walles** [comment]
@ciscohack I'll close this for now.

Feel free to re-open if coloring is still a problem!
