### ISSUE TITLE
`moar --colors=8 > output.txt` doesn't write colors

### ISSUE THREAD

**Issue by timotheecour** [walles/moar#207]
in most programs (eg rg, yq, less etc), there's an option to write colors even if output is redirected (to stdout or a file etc).
Can we either honor the flag `--colors=8` when specified, or add a flag `--usecolors=yes|no|auto` to specify whether coloring should be used (yes would force regardless of stdout redirection, auto would depend on whether stdout is redirected)

I use moar because it just works for syntax highlight (eg use case where other tools fail: https://github.com/mikefarah/yq/issues/1162#issuecomment-2086923873) but now am facing the issue that it doesn't work if I need to redirect it somehow

**Comment by walles** [comment]
What is the `less` command line option for it to force color when redirecting output?

I find that unexpected for a pager, especially `less` which doesn't do any coloring that I'm aware of, so a concrete example would be super!

**Comment by walles** [comment]
@timotheecour if you still want this, feel free to re-open with more info!

**Comment by alkk** [comment]
For example, bat can be forced to always output colors, which is useful for fzf preview:

```sh
fzf --preview "bat --color=always -pp {}"
```
![image](https://github.com/user-attachments/assets/90d7811b-09d9-4a39-9db1-c6f0181cac8a)

But moar does not output colors and there is no way to force it (or I was not able to find it):

```sh
fzf --preview "moar {}"
```

![image](https://github.com/user-attachments/assets/d858b3eb-5b73-4d28-9569-ff81f2132135)

**Comment by walles** [comment]
For this purpose I'd recommend installing Chroma and using that.

https://github.com/alecthomas/chroma?tab=readme-ov-file#command-line-interface 

Chroma is what `moar` uses internally, so this should get you the same highlighting that you get from `moar`.

**Comment by alkk** [comment]
> For this purpose I'd recommend installing Chroma and using that.

Thanks.

**Comment by texastoland** [comment]
> For example, bat can be forced to always output colors, which is useful for fzf preview:

+1 I understand moor is intended to be a modern `less` and overlap w/ bat isn't by design. otoh fzf is quite popular. it'd be convenient to not need another tool. anyway amazing work all these years 🙌
