### ISSUE TITLE
moar doesn't syntax highlight json

### ISSUE THREAD

**Issue by timotheecour** [walles/moar#208]
## moar doesn't syntax highlight json
I thought moar was using chroma to syntax highlight but:
`moar foo.json` doesn't syntax highlight
`cat foo.json|moar --lang json` doesn't syntax highlight

`chroma foo.json` works
`cat foo.json|chroma` works
`cat foo.json|chroma --lexer=json` works

## moar should have a command line option to show what it can syntax highlight
even if it's simply outputting the contents of `chroma --list` (so long that is what it uses, although json bug above casts some doubts)

**Comment by walles** [comment]
Might be fixed in `moar --version` `v1.23.11`, this sounds like what was reported in #202.

Can you do `moar --version`?

**Comment by walles** [comment]
Assuming this was fixed together with #202.
