### ISSUE TITLE
new moar hung for few second while searching

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#209]
In the latest moar, it seems the old search and freeze issue is back. while searching for any keyword CLI freeze for a few seconds.

moar version v1.23.13

**Comment by walles** [comment]
How big is your input?

**Comment by ciscohack** [comment]
it has 5 lakh lines but this search freeze was fixed in old build when last time i reported if you remember..freeze is more evident when you accidently type wrong word not exist in file

**Comment by walles** [comment]
> it has 5 lakh lines

I looked it up, this means five hundred thousand lines right?

**Comment by ciscohack** [comment]
> > it has 5 lakh lines
> 
> I looked it up, this means five hundred thousand lines right?

yes correct!

**Comment by walles** [comment]
I'm not sure if this fixes it, but 1.23.14 should at least be less bad in this regard.

Please try it out and see what you think.

**Comment by ciscohack** [comment]
@walles Thanks

**Comment by walles** [comment]
7b032b2fa4bffe0b7a396040c9d05010e699a8a6 should make the search a lot faster for large files.

That version uses all available cores for searching, rather than just one.
