### ISSUE TITLE
Can't exit after single q or Esc press in Windows

### ISSUE THREAD

**Issue by aNNiMON** [walles/moar#221]
In Windows (git bash, cmd, powershell) single press `q` or `Esc` doesn't immediately closes the program, but pressing any additional key after `q` or `Esc` does.

https://github.com/walles/moar/assets/1321838/2a133c02-6686-4bab-865c-71a66239d23e

**Comment by walles** [comment]
This Windows specific issue should work again in just-out v1.24.6.

**Comment by walles** [comment]
If you can, please help look into #222!
