### ISSUE TITLE
`G` should reload file content

### ISSUE THREAD

**Issue by lapo-luchini** [walles/moar#224]
In `less` pressing `G` goes to the end of the file, but if the file got new lines since opening (e.g. a live log files) it does also load new lines, `moar` at the moment only shows the content at the time of first launch.

**Comment by walles** [comment]
Yes, thanks for pointing this out!

It already works for streams, so until this is implemented for files instead, this will work around it:

```
tail -f file.log | moar
```

**Comment by walles** [comment]
Some work started here, no promises for if or when something will show up in a release:

https://github.com/walles/moar/commits/johan/tail-files/

**Comment by walles** [comment]
This should work in just-released 1.25.0.
