### ISSUE TITLE
Windows version behaves strangely 

### ISSUE THREAD

**Issue by steviator** [walles/moar#227]
Using the latest release 1.25.1 on Windows 10 v. 22H2 (Build 19045.4651), moar is unable to scroll using the keyboard. Any keypress seems to send moar back to the top of the document, while scrolling with the mouse works normally.

This happens with conhost and Windows Terminal (v.1.20.11781.0), as well as Konsole on Linux, so it seems likely to be a bug in moar and not in any particular terminal emulator.

I would very much like to be able to use moar on Windows as it seems to be the only program of its type available for Windows apart from the original more.exe. If it worked, obviously moar would be absolute best in class for applications of this type.

**Comment by walles** [comment]
Can you run `moar` with `--trace` and post the output here?

**Comment by walles** [comment]
The only way for me to work on this @steviator would be to get the `--trace` output.

I have tried to reproduce this but failed. The `--trace` output is likely to tell me what's going on.

**Comment by walles** [comment]
Please reopen if you can get `--trace` output @steviator.

I cannot come up with any other way for me to troubleshoot this.
