### ISSUE TITLE
fish: command help warns about unrecognized ANSI

### ISSUE THREAD

**Issue by charego** [walles/moar#23]
Fish shell [builtin commands](https://fishshell.com/docs/current/commands.html) come with a `--help` option. In many cases, `moar` handles the output fine. In some cases, it warns about "unrecognized ANSI". Is this an issue with `moar` or the output itself?

```
> fish --version
fish, version 3.1.0

> functions --help     # works fine?
> type --help          # works fine?
> set --help           # displays warnings
```
Press `q` immediately to close the pager.
```
Please post the following report at <https://github.com/walles/moar/issues>,
or e-mail it to johan.walles@gmail.com.

Version: 0.9.18
LANG   : en_US.UTF-8
TERM   : xterm-256color

GOOS    : darwin
GOARCH  : amd64
Compiler: gc
NumCPU  : 8

time="2020-03-24T20:07:12-05:00" level=warning msg="Unrecognized ANSI SGR code <24>"
time="2020-03-24T20:07:12-05:00" level=warning msg="Unrecognized ANSI SGR code <24>"
time="2020-03-24T20:07:12-05:00" level=warning msg="Unrecognized ANSI SGR code <24>"
time="2020-03-24T20:07:12-05:00" level=warning msg="Unrecognized ANSI SGR code <24>"
time="2020-03-24T20:07:12-05:00" level=warning msg="Unrecognized ANSI SGR code <24>"
```

Here's how `most` handles the output. It looks like there is something wrong with the output itself.

<img width="715" alt="fish-functions-most" src="https://user-images.githubusercontent.com/5209296/77492215-f1e26e00-6e0d-11ea-8b1a-6381891215be.png">

<img width="718" alt="fish-set-most" src="https://user-images.githubusercontent.com/5209296/77492217-f27b0480-6e0d-11ea-9e86-a30d6e69dcf5.png">

**Comment by walles** [comment]
Just released this fix as 0.9.19: https://github.com/walles/moar/releases/tag/0.9.19

Thanks for reporting @charego!
