### ISSUE TITLE
how to show the searched text in the center of window?

### ISSUE THREAD

**Issue by qbai** [walles/moar#233]
when I search one text by moar, it show the highlight result in the first line of the window, how to set it in the center?
another problem is I can not cancel highlight color by clicking alt+u, how to do that?

**Comment by walles** [comment]
Is this a dup of #132?

**Comment by qbai** [comment]
yes,  that case was opened one year ago, ^_^

**Comment by walles** [comment]
Confirmed dup, closing as dup of #132.
