### ISSUE TITLE
Block input stream

### ISSUE THREAD

**Issue by unphased** [walles/moar#235]
I hate less with a passion for many reasons I won't get into. But for a tool to be a replacement for it, we need to replicate its basic functionality. One of these is that less will only consume some of the top of the input that you send and not the entire input. 

I am on a Ubuntu 20.04 system and finding that OSC 8 hyperlinks are not understood by less 551. So I'm here looking at alternatives. I am glad to report `moar` is handling that aspect well. 

But I immediately saw with my `git log -p` workflow using moar as a pager: 

- upon initial open it starts to consume all 151 thousand lines of input from `git log -p`. Under no circumstances should the computer be doing all the work of having git generate the entire git log and for the pager to consume all of it and waste RAM doing so, until I as the user command it to go to the bottom of the buffer or something to that effect (like less does if I ask it for full progress status with `-M`).
- to rub salt in the wound, interactivity is broken. I try to scroll down with `j` and it is stuck at the top until the 151k lines are consumed.

The way this is supposed to work is that the pager needs to stop consuming input until it really needs to get more in order to display it. This will in turn cause the input stream (the inputting software's output stream) to block. This would also hang the inputting software. That is by design and desired. 

*grumble* i'm going to have to build less from source aren't I? *update*: Building less from source is easier than expected.

**Comment by walles** [comment]
`moar` should be fully interactive while the stream is being consumed.

But now that I try `git log -p` and hammer `j` while the input is being read I agree that scrolling down works badly.

Will look into that.

Thanks for reporting!

**Comment by walles** [comment]
There was an issue with scrolling down while the stream was loading.

Please try just-released v1.25.3, it should work there:
https://github.com/walles/moar/releases/tag/v1.25.3

**Comment by unphased** [comment]
Thanks. that will help. however do you have plans to change the behavior or allow configuring how much of the stream to consume rather than to greedily consume it until the end?

**Comment by walles** [comment]
> do you have plans to change the behavior or allow configuring how much of the stream to consume rather than to greedily consume it until the end?

No.

Reading 150k lines at 500 bytes per line is 75MB, that's nothing (or how much memory do you have on this system?).

And as soon as you search you'll have to read everything anyway, and the user has to wait, breaking interactivity.

Out of curiosity, if there was a memory limit, where would you put it?

**Comment by unphased** [comment]
I don't have any systems I use for serious development that have less than 64GB ram these days. That is beside the point though but also quite happy to agree to disagree on that particular point.
