### ISSUE TITLE
Moar seems to struggle displaying underlines from systemctl

### ISSUE THREAD

**Issue by excited-bore** [walles/moar#237]
**moar** :
![underlines](https://github.com/user-attachments/assets/31a09bd7-db51-4f04-9649-51eb7cf49273)

**less**:
![less_underlines](https://github.com/user-attachments/assets/3a3f385e-f942-4ab1-988f-b139978cc7d8)

**Comment by walles** [comment]
Can you try this with `MOAR=--trace` set as well?

Then `moar` will print logs after exiting.

Please post those logs here!

**Comment by walles** [comment]
Should work in the new release:
https://github.com/walles/moar/releases/tag/v1.26.0
