### ISSUE TITLE
[BUG] CJK charactors support?

### ISSUE THREAD

**Issue by CarterLi** [walles/moar#243]
Simple command results in messy output

`$ ps -ef | moar`

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/abad45fe-5e2d-4a34-b11c-c7609b1f8ced">

It turns out to be caused by the CJK charactors `上午`. If I use `LANG=C ps -ef | moar` it displayed normally

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/6ac657f6-ee3c-4013-950a-05a5dc2c0f7c">

**Comment by CarterLi** [comment]
Reproduce: moar [ps.txt](https://github.com/user-attachments/files/16989576/ps.txt)

**Comment by walles** [comment]
Thanks for the repro!

This could be possible to handle using something like https://github.com/mattn/go-runewidth to figure out string lengths.

No promises for a fix, but I want this to work.

**Comment by walles** [comment]
... which seems to be based on this library: https://github.com/rivo/uniseg

**Comment by CarterLi** [comment]
`wcwidth(3)` can be used in C. Not sure about go though.

**Comment by walles** [comment]
Unrelated note here, if you tend to use `ps`, I can recommend trying my `ps` replacement `px`:

https://github.com/walles/px

**Comment by walles** [comment]
Released in <https://github.com/walles/moar/releases/tag/v1.27.2>.

And you should really try `px` :).
