### ISSUE TITLE
Feature request to format some of language file in proper format while reading using moar

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#247]
Hi Johan,

As you always help me in my problem or feature request. I come up with unusual request to have a feature in moar to format the output in language format when someone use switch --lang while reading a file in moar. Suppose i want to read my long XML code in moar and when I do moar -lang xml <filename> then moar reformat the file according to mention language for better readability

**Comment by walles** [comment]
I have done this for JSON, with the `--reformat` flag.

I think for XML this might be too hard, there's so much about XML I don't understand and I'm afraid I'd just screw up if I tried to format it. Including by using third party libraries for the formatting.

So for XML this is a no, sorry.
