### ISSUE TITLE
Moar does not display white space changes 

### ISSUE THREAD

**Issue by alper** [walles/moar#249]
I'm having a hard time finding something displaying whitespace changes in git diffs.

I run it like: `GIT_PAGER=moar git diff`

Then I get:

![CleanShot 2024-10-02 at 12 46 16@2x](https://github.com/user-attachments/assets/06005f44-f8d5-4a1b-a776-32dbe833725e)

I already tried: -render-unprintable value=highlight

**Comment by walles** [comment]
Can you post the diff as well?

Just do `git diff | cat` and post the output here?

**Comment by walles** [comment]
Did you try https://github.com/walles/riff for highlighting this diff?

It's designed for making diffs more helpful.

If that doesn't show the white space change I'll need to know what actually changed to be able to do anything here.

And any change I make related to this is likely to be in `riff`.

**Comment by alper** [comment]
OK. Not sure why it's different on my home machine, but this is what I could reproduce:

pager=cat

![CleanShot 2024-10-06 at 18 14 39@2x](https://github.com/user-attachments/assets/161e6eaf-d8b5-4a22-afa2-6f545265f789)

pager=moar

![CleanShot 2024-10-06 at 18 14 54@2x](https://github.com/user-attachments/assets/e44f5e69-28c6-4481-89c7-afb039708791)

pager=delta

![CleanShot 2024-10-06 at 18 15 10@2x](https://github.com/user-attachments/assets/9b81e9e4-a2d6-43cd-9107-9e6bd02553cf)

So all three of them show the trailing space which is odd since I felt it was very hard on my work machine to get the trailing space to be displayed.

**Comment by walles** [comment]
I'm really at a loss regarding what to do here.

If this still repros on your work machine, are you running some other terminal there than at home?

Terminal differences is a possible (but not likely I'd say) explanation here.

I have run `moar` with multiple different terminals but I don't recall ever seeing this problem.

**Comment by alper** [comment]
I don't think anything needs to be done here. I'll check if I can reproduce it on the other machine and in the mean time close this ticket.
