### ISSUE TITLE
Suggestion: horizontal scrolling with Vim keys

### ISSUE THREAD

**Issue by Randoragon** [walles/moar#25]
I've just discovered moar, and it does exactly what it advertises itself for, but having to scroll horizontally with arrow keys is very cumbersome. I would suggest having vim keys for horizontal scrolling (h - left, l - right). The help keybinding could be moved anywhere else (maybe question mark key or F1?), it's not used very often and I would argue that more people hit 'h' thinking it's horizontal scroll than those who actually need help.

**Comment by walles** [comment]
Released as `0.9.23`:
<https://github.com/walles/moar/releases/tag/0.9.23>

**Comment by walles** [comment]
Thanks for the suggestion @Randoragon!

**Comment by joelpeapen** [comment]
Horizontal scrolling with `h` and `l` keys no longer works. The last working release is v1.29.0

**Comment by joelpeapen** [comment]
in my opinion, using `h` and `l` makes moar sense because `less` already uses `j` and `k` to scroll up and down.

it would be trivial for `less` users to use `?` instead of `h`
