### ISSUE TITLE
[suggestion] Show example of configuration on windows

### ISSUE THREAD

**Issue by milnak** [walles/moar#251]
e.g.

On Windows, edit `$PROFILE` and add `PAGER` and `MOAR` environment variable settings.

If one installed moar via [scoop](https://scoop.sh) ("scoop install extras/moar"), the following can be used.

`notepad $PROFILE`

```PowerShell
$moar = scoop which moar.exe
if ($moar) {
  $env:PAGER=(Resolve-Path $moar)
  # See https://xyproto.github.io/splash/docs/longer/all.html
  $env:MOAR='--style=rrt'
}
```

**Comment by walles** [comment]
Now out in v1.27.3 if you want to test it.

Thanks for reporting!
