### ISSUE TITLE
Please don't reformat files by default

### ISSUE THREAD

**Issue by CarterLi** [walles/moar#253]
`moar` is advertised to be a pager, not a code formatter. Sometimes I want to make sure my JSON file is correctly formatted or minimalized and double check it with `cat`. Reformatting my files by default is highly misleading.

**Comment by haunt98** [comment]
I agree too. Format should be off by default.

**Comment by walles** [comment]
Thanks for bringing this up!

First of all, the decision to make this default was mostly arbitrary. I don't know where I would get data to make an informed one, suggestions welcome.

This said, two questions for both of you (and if anybody else shows up):
1. Are you running `moar` on your own machine, or do you have it on remote machines that you `ssh` into (or whatever)?
2. How would setting `MOAR=--no-reformat` in the environment work for you? Easy, impractical (why?), something else?

Cred for providing a use case @CarterLi!

**Comment by haunt98** [comment]
I run moar on my machine only, and set up new flag to disable json is not hassle for me.

**Comment by CarterLi** [comment]
1. Both.
2. You said [`Moar is a pager`](https://github.com/walles/moar/blob/master/README.md). [A pager](https://en.wikipedia.org/wiki/Terminal_pager) should print the file content accurately. If I want to pretty printing a JSON file, I have `jq` or other tools. Please [keep it simple and stupid](https://en.wikipedia.org/wiki/KISS_principle)

Otherwise, you may change the description to `Moar is a pager and randomly reformat some type of files`
