### ISSUE TITLE
String input

### ISSUE THREAD

**Issue by 89z** [walles/moar#31]
I am trying to write a program using the Moar package. I did this:

~~~go
package main

import (
   "github.com/gdamore/tcell/v2"
   "github.com/walles/moar/m"
)

func main() {
   read_o := m.NewReaderFromText("March", "April")
   screen := tcell.NewSimulationScreen("UTF-8")
   page_o := m.NewPager(read_o)
   page_o.StartPaging(screen)
}
~~~

The program just runs with no output, looks like its waiting for input. Is what I am trying to do possible?

**Comment by 89z** [comment]
Workaround:

~~~go
package main

import (
   "fmt"
   "log"
   "os"
   "os/exec"
)

func main() {
   less_o := exec.Command("less")
   pipe_o, e := less_o.StdinPipe()
   if e != nil {
      log.Fatal(e)
   }
   less_o.Stdout = os.Stdout
   less_o.Start()
   fmt.Fprint(pipe_o, "March April")
   pipe_o.Close()
   less_o.Wait()
}
~~~

**Comment by walles** [comment]
See below for an example that works for me.

The issue with your code was that you were creating a for-testing-only `SimulationScreen`, which doesn't interact with the terminal.

Other than that, in my example below I pass "Months" to the `Reader`'s `name` parameter. This will be displayed in the bottom left corner of the screen.

I also added a newline in your example string to demonstrate how multi line works.

Very cool that you are embedding `moar`, in retrospect it's an obvious use case but I never thought of it. Thanks @89z! 

I'm closing this, do re-open if it still doesn't work for you!

```go
package main

import (
	"github.com/gdamore/tcell/v2"
	"github.com/walles/moar/m"
)

func main() {
	read_o := m.NewReaderFromText("Months", "March, April\nMay")

	screen, e := tcell.NewScreen()
	if e != nil {
		// Handle screen setup errors
		panic(e)
	}
	defer screen.Fini()

	page_o := m.NewPager(read_o)
	page_o.StartPaging(screen)
}
```

**Comment by walles** [comment]
Added docs for how to embed `moar`: <https://github.com/walles/moar#embedding>

**Comment by 89z** [comment]
Very cool! Thank you!

Many projects I see (even Git itself) shell out to Less, and I was wondering
why to myself. It seems poor practice to shell out if a library is available. I
dont know of any "LibLess", so I went around searching if something like that
exists. I found one or two brand new projects in Rust, and a couple of options
(Moar being one) in Go.

Another question. The `PageString` method is cool, but it would be nice if we
also have a `PageReader`, then we can do something like this:

~~~go
package main

import (
   "github.com/gdamore/tcell/v2"
   "github.com/walles/moar/m"
   "io"
   "os/exec"
)

func PageReader(stream io.Reader, fromFilter *exec.Cmd) error {
   reader := m.NewReaderFromStream(stream, fromFilter)
   screen, e := tcell.NewScreen()
   if e != nil {
      return e
   }
   defer screen.Fini()
   m.NewPager(reader).StartPaging(screen)
   return nil
}
~~~

Then we could do this:

~~~go
package main

import (
   "bytes"
   "fmt"
   "log"
)

func main() {
   buf := bytes.Buffer{}
   fmt.Fprintln(&buf, "March")
   fmt.Fprintln(&buf, "April")
   e := PageReader(&buf, nil)
   if e != nil {
      log.Fatal(e)
   }
}
~~~

**Comment by walles** [comment]
I just updated the embedding API to something I think should be easy and somewhat flexible to use.

New example from here: <https://github.com/walles/moar#embedding>

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/walles/moar/m"
)

func main() {
	buf := bytes.Buffer{}
	fmt.Fprintln(&buf, "March")
	fmt.Fprintln(&buf, "April")

	name := "Months"
	err := m.Page(m.NewReaderFromStream(&name, &buf))
	if err != nil {
		// Handle paging problems
		panic(err)
	}
}
```

**Comment by 89z** [comment]
that is pretty cool, thanks! Small nitpick, I just noticed that `NewReaderFromStream` takes a string pointer for the first argument? I guess I didnt notice that before. Usually thats only done when the method is modifying the argument. Wondering what the thinking was in that case.

**Comment by walles** [comment]
In this case, the reason for the pointer is to enable passing `nil`.

Not sure how to clarify this better in the code, is there another better way of saying "no name is fine"?

Accepting an empty string and adding a comment about that maybe?

Or keeping the pointer and clarify in comments?

**Comment by 89z** [comment]
Ideally the optional argument should come after the required argument. Then you
can do something like this:

~~~go
package main
import "fmt"

func Printf(required string, optional ...interface{}) {
   fmt.Printf(required, optional...)
}

func main() {
   Printf("March\n")
   Printf("%v\n", "April")
}
~~~

**Comment by walles** [comment]
I opted for:
* Having `string` rather than `*string` as the `name` parameter
* Allowing `""` as a name
* Documenting allowing the empty string as a name

Thanks for providing opinions about the API @89z, I really appreciate your feedback!

**Comment by walles** [comment]
What I'd *really* like is to use optional arguments, but they are not part of the language: <https://stackoverflow.com/questions/2032149/optional-parameters-in-go>

Using variadic functions wouldn't really convey the meaning here IMO.

They totally have their place in `printf()` like functions where you have an arbitrary number of parameters, or in functions working on arrays, but in this case when it's a single named and typed parameter that should or should not be provided I don't think they provide what I want.

**Comment by 89z** [comment]
Not sure what you have in mind, but if you are wanting to enforce 0 or 1 values,
and also allow `nil`, you could do something like this:

~~~go
package main

import (
   "fmt"
   "log"
)

func Printf(required string, optional ...interface{}) error {
   n := len(optional)
   if n > 1 {
      return fmt.Errorf("%v values but optional expects 0 or 1 values", n)
   }
   if n == 1 && optional[0] == nil {
      fmt.Printf(required)
      return nil
   }
   fmt.Printf(required, optional...)
   return nil
}

func main() {
   Printf("March\n")
   Printf("March\n", nil)
   Printf("%v\n", "April")
   e := Printf("%v\n", "April", "May")
   if e != nil {
      log.Fatal(e)
   }
}
~~~
