### ISSUE TITLE
Unrecognized ANSI SGR code <2>

### ISSUE THREAD

**Issue by muralikodali** [walles/moar#32]
I have executed following command in terminal (alacritty).

```
stash list --pretty=format:\"%C(red)%h%C(reset) - %C(dim yellow)(%C(bold magenta)%gd%C(dim yellow))%C(reset) %<(70,trunc)%s %C(gree  n)(%cr) %C(bold blue)<%an>%C(reset)\"
```
output is as follows :  

Version: 0.9.23
LANG   : en_US.UTF-8
TERM   : xterm-256color

GOOS    : linux
GOARCH  : 386
Compiler: gc
NumCPU  : 4

time="2020-12-23T19:18:53+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"
time="2020-12-23T19:18:53+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"
time="2020-12-23T19:18:53+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"
time="2020-12-23T19:18:53+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"
time="2020-12-23T19:18:53+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"
time="2020-12-23T19:18:53+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"
time="2020-12-23T19:18:53+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"
time="2020-12-23T19:18:53+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"
time="2020-12-23T19:18:54+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"
time="2020-12-23T19:18:54+05:30" level=warning msg="Unrecognized ANSI SGR code <2>"

**Comment by walles** [comment]
This should work in 1.1, try upgrading to the latest version!

**Comment by muralikodali** [comment]
Thanks, no problem after upgrading to 1.1
