### ISSUE TITLE
Exit without clear screen

### ISSUE THREAD

**Issue by 89z** [walles/moar#33]
If I have this code:

~~~go
package main

import (
   "github.com/walles/moar/m"
   "strings"
)

func main() {
   m.Page(m.NewReaderFromText("dir", strings.Repeat("north\n", 50)))
}
~~~

when I exit, the screen is cleared. I tried changing to this:

~~~go
package main

import (
   "github.com/gdamore/tcell/v2"
   "github.com/walles/moar/m"
   "log"
   "strings"
)

func main() {
   r := m.NewReaderFromText("dir", strings.Repeat("north\n", 50))
   s, e := tcell.NewScreen()
   if e != nil {
      log.Fatal(e)
   }
   m.NewPager(r).StartPaging(s)
}
~~~

but now when I exit, my shell prompt has partially overwritten the last line, the colors are inverted, and the cursor is missing. This is possible with other tools like Less, where you can specify `-X` option or `LESS=X` environment variable:

https://serverfault.com/questions/785949

**Comment by walles** [comment]
Related to <https://github.com/gdamore/tcell/issues/262>.

**Comment by walles** [comment]
The current shutdown sequence for TCell's `Screen` object is rather involved, not sure how much it should be replicated / messed with:

<https://github.com/gdamore/tcell/blob/29bb185874fd86b7d0a5b57e1a17d6f8ed9a9040/tscreen.go#L472-L498>

As you noticed, just not calling it seems not to be an option.

**Comment by 89z** [comment]
Im not convinced that its totally an upstream problem.

I played with this a lot yesterday, and it seems Moar is doing some Voodoo that
isnt normally done with stock Tcell. If you try out the Boxes demo:

https://github.com/gdamore/tcell/blob/master/_demos/boxes.go

its pretty aggressive, as it puts different colored boxes all over the screen.
Even with that nonsense, I was able to get a clean exit like this:

~~~go
// carriage return
print("\r")
// reset color
print("\x1b[m")
// clear line
print("\x1b[K")
// show cursor
print("\x1b[?25h")
~~~

Notice the line for the shell prompt has proper color, and the cursor can be
seen:

> ![good](https://user-images.githubusercontent.com/73562167/103297520-18958c80-49be-11eb-926b-d48535472e6c.png)

but if I use the same code with Moar:

~~~go
package main

import (
   "github.com/gdamore/tcell/v2"
   "github.com/walles/moar/m"
   "log"
   "strings"
)

func main() {
   reader := m.NewReaderFromText("Months", strings.Repeat("March\n", 100))
   screen, e := tcell.NewScreen()
   if e != nil {
      log.Fatal(e)
   }
   m.NewPager(reader).StartPaging(screen)
   print("\r")
   print("\x1b[m")
   print("\x1b[K")
   print("\x1b[?25h")
}
~~~

On exit, Moar clobbers the last line `40 March`, the colors arent reset, the
line isnt cleared, and the cursor is visible, but its all the way to the right
for some reason. I put before and after screenshots:

> ![before](https://user-images.githubusercontent.com/73562167/103297853-bdb06500-49be-11eb-8575-286c6825a82b.png)

> ![after](https://user-images.githubusercontent.com/73562167/103297737-8d68c680-49be-11eb-86a0-717e1dd524c9.png)

**Comment by walles** [comment]
I don't *think* I'm doing anything strange but I have only tested `moar` on macOS and Linux, don't have access to any Windows box.

If this should work on Windows as well having it done by upstream would likely be better!

**Comment by 89z** [comment]
If you have VirtualBox, you can get an ISO here:

https://superuser.com/questions/1108085#1108086

**Comment by 89z** [comment]
I found a workaround, this package also used `Fini`:

https://github.com/noborus/ov

but if you remove it, you still get a clear exit. But it doesnt do stuff with reversing the color, so maybe that has something to do with it.

**Comment by walles** [comment]
`moar` enables mouse interaction, that could potentially add requirements for the shutdown sequence.

**Comment by 89z** [comment]
I tried adding this, but it didnt seem to change anything:

~~~go
ti, e := terminfo.LookupTerminfo("xterm-256color")
if e != nil {
   log.Fatal(e)
}
ti.TPuts(os.Stdout, ti.TParm(ti.MouseMode, 0))
~~~

**Comment by walles** [comment]
Things I would imagine being needed to get out clean include:
* Drop inverse, colors, etc: [`AttrOff`](https://github.com/gdamore/tcell/blob/29bb185874fd86b7d0a5b57e1a17d6f8ed9a9040/terminfo/terminfo.go#L55) / `SGR 0`
* Move cursor to bottom left corner of terminal window
* Cooked mode, not raw mode (unsure about this one, not sure what it actually is, but maybe needed)
* Make cursor visible
* Print an empty line to scroll screen up one notch to make room for the prompt

But I just made this list up freely, so things might be missing / redundant.

**Comment by 89z** [comment]
I put a few hours into this already, I think I pretty much tried all of those
at one point or another. I think for now I might look into doing a PR on
`noborus/ov`, and just using that. Its too bad that Tcell hasnt implemented a
method for this, as Less has had an option for this for at least 25 years:

https://github.com/gwsw/less/blob/fe6f7985/opttbl.c#L218-L222

**Comment by 89z** [comment]
I think I found a workaround for this. With this other package, the screen is also cleared on close. However it saves the state of the screen, and you can write it out after close:

https://pkg.go.dev/github.com/noborus/ov/oviewer#Root.WriteOriginal

Does Moar have something like that?

**Comment by walles** [comment]
I'll let @gdamore answer in the upstream `tcell` issue since that's where the shutdown code lives.

**Comment by 89z** [comment]
I dont understand the comment? Are you able to answer if Moar itself currently has a function like what I described above?

**Comment by walles** [comment]
`moar` itself does not, sorry.

**Comment by 89z** [comment]
I finally got this working. Here is example:

~~~go
package main

import (
   "github.com/gdamore/tcell/v2"
   "github.com/walles/moar/m"
   "log"
   "strings"
)

func main() {
   t := strings.Repeat("south north\n", 50)
   r := m.NewReaderFromText("direction", t)
   s, e := tcell.NewConsoleScreen()
   if e != nil {
      log.Fatal(e)
   }
   m.NewPager(r).StartPaging(s)
   // clean up without clearing screen
   print("\r\x1b[m")
   _, y := s.Size()
   s.ShowCursor(0, y - 1)
   s.SetContent(0, y - 1, '\r', nil, tcell.StyleDefault)
   s.Show()
}
~~~

The last lines seem to produce the same result as Less. The final line is
clobbered and replaced with command prompt, other lines are not touched.

**Comment by 89z** [comment]
https://github.com/walles/moar/pull/39
