### ISSUE TITLE
m package is now broken

### ISSUE THREAD

**Issue by 89z** [walles/moar#45]
Using this test:

~~~go
package m

import (
   "bytes"
   "fmt"
   "testing"
)

func TestPage(t *testing.T) {
   buf := new(bytes.Buffer)
   for range [99]struct{}{} {
      fmt.Fprintln(buf, "Moar")
   }
   NewPager(NewReaderFromStream("Moar", buf)).Page()
}
~~~

I am getting complete failures for the last 13 commits:

~~~
60da229 no output
39ab1fc no output
2f0df18 panic
1b292fa panic
4e8c49e panic
1e46089 panic
ff9380f panic
9e0d48e panic
9b86fc5 panic
9f9dc37 panic
e5ec2ce non-name screen.ttyIn on left side of :=
e72baff syscall.Open returns 2 values
90e3746 panic
44a064c good
~~~

**Comment by walles** [comment]
The `Page()` method now returns an error code.

With 44dc59d36545b5b71d846aa28129432d1ebfa85e I clarified that error code to `stdout (fd=1) must be a terminal for paging to work`.

When running tests, `stdout` is no terminal (at least when I run tests).

If you try this with a non-test program you should be fine.

**Comment by 89z** [comment]
So... How do you test the `Page` method?

**Comment by walles** [comment]
I use a `FakeScreen`:
https://github.com/walles/moar/blob/44dc59d36545b5b71d846aa28129432d1ebfa85e/m/pager_test.go#L88-L103

**Comment by 89z** [comment]
ok I think I sorted it. I downloaded the zip:

https://github.com/walles/moar/archive/refs/heads/master.zip

and extract, then I make a new file:

~~~
m/moar/moar.go
~~~

like this:

~~~
package main

import (
   "bytes"
   "fmt"
   "github.com/walles/moar/m"
)

func main() {
   buf := new(bytes.Buffer)
   for range [99]struct{}{} {
      fmt.Fprintln(buf, "Moar")
   }
   m.NewPager(m.NewReaderFromStream("Moar", buf)).Page()
}
~~~

and I am able to test like you say. I just wanted to make sure I was using the latest version, and I dont like doing the whole `go get` thing or whatever. I just like working from the local files sometimes.
