### ISSUE TITLE
Moar is slow

### ISSUE THREAD

**Issue by 89z** [walles/moar#46]
I was hoping that removing Tcell would have helped, but it did not. Here is the test I use:

~~~go
package main

import (
   "fmt"
   "github.com/walles/moar/m"
   "strings"
   "time"
)

func main() {
   s := strings.Repeat("Text\n", 200)
   t := time.Now()
   m.NewPager(m.NewReaderFromText("Text", s)).Page()
   fmt.Println(time.Since(t))
}
~~~

Here is test I use with another project [1]:

~~~go
package main

import (
   "fmt"
   "github.com/noborus/ov/oviewer"
   "strings"
   "time"
)

func main() {
   read := strings.NewReader(strings.Repeat("Text\n", 200))
   root, e := oviewer.NewRoot(read)
   if e != nil {
      panic(e)
   }
   t := time.Now()
   root.Run()
   fmt.Println(time.Since(t))
}
~~~

For my tests, I start the program, press and hold the down arrow, then once at the bottom, hit `q` to quit. Results:

~~~
Moar: 6.0362189s
Ov: 3.4086349s
~~~

1. https://github.com/noborus/ov

**Comment by walles** [comment]
I just did a related experiment:

# 1. Terminal
1. Count lines in `moar.go`. It contains 190 lines.
2. Make my terminal window 190/2=95 columns wide
3. Type two lines (190 characters) of gibberish
4. Go to start of line
5. Press and hold right arrow key

# 2. Visual Studio Code
Hold down arrow and count how long it takes to get from line 1 to line 190 of `moar.go`

# Result (counting in my head, very unscientific):
* Right-arrow test: 6s
* Down-arrow, VSCode: 6s

These numbers match `moar`'s performance AFAICT.

For faster scrolling, I use the mouse wheel, would that help you? Or how is `moar` vs the terminal / vscode on your machine?

**Comment by 89z** [comment]
I am not understanding how your tests relate to mine.

It seems that Moar does more "processing" or something than Ov, as I can scroll Down with Ov much faster.

Also I dont understand why you did tests with moving right, and the width. Again this is about moving down, not about moving right, and not about Visual Studio Code.

**Comment by walles** [comment]
I think the limit here is your machine's key repeat speed.

I believe that `moar` scrolls down one line every time it gets a key down event, just like other major apps like Visual Studio Code and your terminal.

So the tests I suggested are verifying your machine's key repeat speed.

If you can show that `moar` scrolls *slower* than your key repeat speed settings, I'll look into it.

**Comment by 89z** [comment]
Regardless of my key repeat speed, why would Moar be half the speed of the other package?

**Comment by 89z** [comment]
I think I figured it out. When you press down with Oviewer, `moveDown` is called:

https://github.com/noborus/ov/blob/98f0ab68/oviewer/move.go#L196-L197

which should move the screen down one line, but is actually moving the screen down two lines from my testing. So while its technically an error, for me its desired behavior.

Does Moar have a way to control the number of lines scroll with the down key?

**Comment by walles** [comment]
> Does Moar have a way to control the number of lines scroll with the down key?

Not other than PgUp, PgDown, `u` (half page up) and `d` (half page down).
