### ISSUE TITLE
Fix version tag

### ISSUE THREAD

**Issue by 89z** [walles/moar#47]
Current tag is 1.3:

https://github.com/walles/moar/releases/tag/1.3

However this format of tag is not valid for Go modules. Proper format would be:

~~~
v1.3.0
~~~

because of this, importing Moar looks like this:

~~~
github.com/walles/moar v0.0.0-20210420071802-54942cf12ea3
~~~

and the documentation shows no tagged version is available:

https://pkg.go.dev/github.com/walles/moar/m

**Comment by walles** [comment]
Done in `v1.3.1`: <https://github.com/walles/moar/releases/tag/v1.3.1>

Thanks for reporting @89z!
