### ISSUE TITLE
Invalid stdin error message

### ISSUE THREAD

**Issue by 89z** [walles/moar#49]
Using this file:

~~~go
package m

import (
   "strings"
   "testing"
)

func TestPage(t *testing.T) {
   s := strings.Repeat("Moar\n", 99)
   r := NewReaderFromText("Moar", s)
   e := NewPager(r).Page()
   if e != nil {
      t.Error(e)
   }
}
~~~

I get this result:

~~~
--- FAIL: TestPage (0.00s)
    page_test.go:13: Getting piped data on stdin is not supported on Windows,
fixes needed in here:
https://github.com/walles/moar/blob/walles/fix-windows/twin/screen-setup.go
~~~

However it seems the error message is invalid, as I am feeding data from a string, not from standard input.

**Comment by 89z** [comment]
As a workaround, I did a `git bisect`, this is the first bad version:

~~~
From 90e374601de59098e0a84f4ba0caaf3c64ce49e5 Mon Sep 17 00:00:00 2001
From: Johan Walles <johan.walles@gmail.com>
Date: Thu, 15 Apr 2021 15:16:06 +0200
Subject: [PATCH] Use our new tcell replacement
~~~

https://github.com/walles/moar/commit/90e374601de59098e0a84f4ba0caaf3c64ce49e5

**Comment by walles** [comment]
The link in that message was wrong and the phrasing was bad, the message should be fixed now I think (after two attempts...) sorry about that.

The problem still exists though.

It's this code that's being referred to:
https://github.com/walles/moar/blob/a211a28f494c9fa8c7c8281e2bb3c6bec80fc228/twin/screen-setup-windows.go#L22-L32

**Comment by 89z** [comment]
It's bedtime for me, will try to look at this tomorrow. In the meantime, do you know why it worked before with Tcell, but not now with Twin?

**Comment by walles** [comment]
At least on Unix they did some changes in recent versions around this that broke piping and prevented me from upgrading, so:

**Honest answer**: No

**Dodging answer**: It wasn't obvious to the tcell people either

**Comment by 89z** [comment]
Looks like the previous implementation is here:

https://github.com/gdamore/tcell/blob/299cb413/console_win.go#L161

did you look at that already?
