### ISSUE TITLE
Wrapping long lines

### ISSUE THREAD

**Issue by tigra** [walles/moar#5]
Is is possible to switch between wrapping long lines and chopping them (in less, achieved with "-S")?
Haven't find this feature.

**Comment by walles** [comment]
Not currently, no, you'll have to scroll sideways to see the ends of the long lines just like with `less -S`.

Can you describe the situation in which you prefer wrapping to scrolling left / right?

What's your use case? What kind of text are you looking at, how large is your window, how far do you need to scroll sideways to see what you want etc?

**Comment by Hund** [comment]
Reading articles is re
lly annoying when th
ey're cut in half like t
is.

**Comment by walles** [comment]
@Hund, `moar` doesn't support what you are reporting.

Can you provide a screenshot?

Also, it seems you have the opposite problem of what's being reported in this ticket, maybe open another one?

**Comment by Hund** [comment]
I know. That's why I replied to this ticket where someone else asked for it as well.

**Comment by walles** [comment]
Please provide a screenshot of `moar` doing what you don't want.

**Comment by Hund** [comment]
Ops. I was trying out several options and it looks like I mixed up `moar` and `most`. It was `moar` that I couldn't use.

```
$ ./moar-0.9.6.rb <file>
/usr/lib64/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- curses (LoadError)
	from /usr/lib64/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./moar-0.9.6.rb:9:in `<main>'
```

Do you want me to create a new issue for it? :)

**Comment by walles** [comment]
Please do @Hund!

**Comment by walles** [comment]
@tigra, care to explain your use case?

Can you describe the situation in which you prefer wrapping to scrolling left / right?

What kind of text are you looking at, how large is your window, how far do you need to scroll sideways to see what you want etc?

**Comment by walles** [comment]
Closed because I don't understand the request.
