### ISSUE TITLE
Propagate errors to main

### ISSUE THREAD

**Issue by 89z** [walles/moar#56]
Instead of just logging errors:

https://github.com/walles/moar/blob/5e49329110267dedb9fd5bacc32de4c3d92000b4/m/ansiTokenizer.go#L464-L467

I wonder if you have considered propagating the errors up to `main`. For example, this would be the call graph for `updateStyle`:

~~~
1. "github.com/walles/moar/m/graph.main"
2. "(*github.com/walles/moar/m.Pager).Page"
3. "(*github.com/walles/moar/m.Pager).StartPaging"
4. "(*github.com/walles/moar/m.Pager)._OnRune"
5. "(*github.com/walles/moar/m.Pager)._ScrollToPreviousSearchHit"
6. "(*github.com/walles/moar/m.Pager)._ScrollToNextSearchHit"
7. "(*github.com/walles/moar/m.Pager)._OnSearchRune"
8. "(*github.com/walles/moar/m.Pager)._OnKey"
9. "(*github.com/walles/moar/m.Pager)._OnSearchKey"
10. "(*github.com/walles/moar/m.Pager)._UpdateSearchPattern"
11. "(*github.com/walles/moar/m.Pager)._ScrollToSearchHits"
12. "(*github.com/walles/moar/m.Pager)._FindFirstHitLineOneBased"
13. "(*github.com/walles/moar/m.Pager)._Redraw"
14. "(*github.com/walles/moar/m.Pager)._AddLines"
15. "(*github.com/walles/moar/m.Pager)._AddLines"
16. "(*github.com/walles/moar/m.Pager)._AddLine"
17. "github.com/walles/moar/m.createScreenLine"
18. "(*github.com/walles/moar/m.Line).Plain"
19. "github.com/walles/moar/m.withoutFormatting"
20. "github.com/walles/moar/m.SetManPageFormatFromEnv"
21. "github.com/walles/moar/m.SetManPageFormatFromEnv"
22. "github.com/walles/moar/m.termcapToStyle"
23. "(*github.com/walles/moar/m.Line).Tokens"
24. "github.com/walles/moar/m.cellsFromString"
25. "github.com/walles/moar/m.styledStringsFromString"
26. "github.com/walles/moar/m.updateStyle"
~~~

If this is something you are open to, I could work on a Pull Request.

**Comment by walles** [comment]
In this particular case, when we get an ANSI code we can't handle, I think the best thing is:
1. Ignore this ANSI request and display without it
2. Tell the user afterwards that we ignored it

And the way logging is set up, all log messages are printed after the user exits, so this is precisely what we get:
https://github.com/walles/moar/blob/5e49329110267dedb9fd5bacc32de4c3d92000b4/moar.go#L198-L205

That way:
1. Users can still use `moar` even if some functionality is lacking
2. We get tickets about it so we can fix it

So at least when `moar` is used as a standalone pager this works as designed.

If you're using `moar` via the embedding UI I'm not so sure, feedback welcome!

**Comment by 89z** [comment]
I think your justification is good. Maybe we could implement a "strict mode", but it seems both approaches are valid in different cases.
