### ISSUE TITLE
Homebrew packaging <- This means you!

### ISSUE THREAD

**Issue by walles** [walles/moar#63]
It would be nice if one could just `brew install moar` and have `moar` being kept up to date automatically rather than [downloading binaries](https://github.com/walles/moar/releases/latest).

For this to happen, `moar` needs to be [packaged for Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-add-a-new-formula-for-foo-version-234-from-url).

And since [the Homebrew maintainers frown on authors submitting their own work unless it is very popular](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff), and `moar` might not be "very popular", this has to be done by `$NOT_JOHAN`.

# Help Wanted <- This means you!

Kindly package `moar` for Homebrew because I (being `moar`'s main author) can't.

**Comment by 89z** [comment]
Hey, I can do this, but I dont know how - any advice?

**Comment by fredericrous** [comment]
in the mid time you could use taps => https://docs.brew.sh/Taps
It's what does https://github.com/trntv/sshed/ (with the use of https://goreleaser.com/customization/homebrew/ )

**Comment by walles** [comment]
Now available in Homebrew core:
* `brew install moar`
* <https://formulae.brew.sh/formula/moar>
