### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#66]
Hi Experts,

Can we have style options like we have in BAT tool  to render a file in a way looks in screnshot or can be refer BAT style options.

![image](https://user-images.githubusercontent.com/11479557/124014568-502ed100-da01-11eb-9635-b1c01880a650.png)

**Comment by walles** [comment]
Have you tried the `--style` option?

Is that what you're after?

```sh
$ moar --help
Usage:
  moar [options] <file>
  ... | moar
  moar < file

Environment:
  Additional options are read from the MOAR environment variable if set.
  But currently, the MOAR environment variable is not set.

Options:
  -colors string
    	Highlighting palette size: 8, 16, 256, 16M (default "16M")
  -debug
    	Print debug logs after exiting
  -no-linenumbers
    	Hide line numbers on startup, press left arrow key to show
  -style string
    	Highlighting style from https://xyproto.github.io/splash/docs/longer/all.html (default "native")
  -trace
    	Print trace logs after exiting
  -version
    	Prints the moar version number
  -wrap
    	Wrap long lines
$
```

**Comment by ciscohack** [comment]
@walles  Thanks for response my friend. yes i have seen and tried but not seeing any effect or might be doing something wrong. can you show us some example of these options.

This is how i tried moar -style dracula -wrap <filename> i believe this should render dracula theme style but i still see my terminal theme style and bat if you see they have lines as seperator between line number horizontal and vertical both

**Comment by walles** [comment]
Can you post:
1. The exact command line you're running? `moar -style dracula -wrap` is not complete, it lacks aa file name. Please copy from your terminal.
2. A screenshot of what `moar` looks like with that command line. Whole window, including title and borders please.

**Comment by ciscohack** [comment]
@walles I left file name intensionally as i was just trying to show you the moar command option only to see whether i am writing right or not. here style look like

![image](https://user-images.githubusercontent.com/11479557/124069572-0920fa00-da5a-11eb-8f23-3dda6d2915a8.png)

**Comment by walles** [comment]
Please post what I asked.

**Comment by ciscohack** [comment]
My friend i am running command "moar -style dracula -wrap shure.log" and once i hit enter display is very similar to what i posted above in screenshot. no border line and title showing for me

**Comment by walles** [comment]
What exact command line did you use to get the screenshot with the lines in it and `2020` highlighted?

**Comment by walles** [comment]
What I'm after is, what is it that is coloring `2020`?

Is it ITerm? Is it BAT? Something else?

**Comment by ciscohack** [comment]
> What I'm after is, what is it that is coloring `2020`?
> 
> Is it ITerm? Is it BAT? Something else?

I used hypterterm and BAT with script to highlight colors in first screenshot. but the borders is due to BAT tool.

**Comment by walles** [comment]
Can you get me a screenshot of *the complete window* when you run BAT in the macOS Terminal?

**Comment by ciscohack** [comment]
here you go.

![image](https://user-images.githubusercontent.com/11479557/124077405-1f808300-da65-11eb-8173-64ae50264513.png)

**Comment by walles** [comment]
Some observations:
1. I don't see any colored `2020` in there.
2. `moar` isn't involved.

So my conclusion is that your coloring problems are related to HyperTerm.

But since this isn't the same file as before it's hard to tell. Try again with:
* macOS Terminal
* Same log file as before
* Screenshot of the whole window, **including borders and title**

**Comment by ciscohack** [comment]
@walles May i know why you focusing on color part i didn't ask moar is not showing color and all. macOS terminal not showing color becoz i didn't used the trigger for coloring. Here my request is to show the border style the way BAT is showing.

**Comment by walles** [comment]
What you asked for initially was "style options". I assumed you were referring to colors.

`moar`'s `--style` option affects colors only, so that won't help you.

Regarding those lines:
* They take up screen real estate
* I don't see the value they provide
* They make copying multiple lines harder

So I'm inclined to say "no" here.

**Comment by ciscohack** [comment]
Okay i understood your point now ..Thanks

**Comment by ciscohack** [comment]
please close the thread ..thanks for the help

**Comment by ciscohack** [comment]
@walles  Sorry bothering you .. is it possible in near future more support .gz files to read the logs compressed with .gz extension or any other compression extension. Currently i use zless command to read without uncompressing it

**Comment by walles** [comment]
If you open any file with a `.gz` extension then `moar` will decompress it as it reads it.

**Comment by ciscohack** [comment]
Okay thanks i didn't find in help section and also on your git page ..sorry. is it possible no decompress instead it's just read the content

**Comment by walles** [comment]
Well spotted, `README.md` updated!

**Comment by walles** [comment]
And the `--help` message, will go into next release.
