### ISSUE TITLE
Drop logrus

### ISSUE THREAD

**Issue by 89z** [walles/moar#68]
Not sure whats going on, but Im getting import errors now:

~~~
        github.com/walles/moar/m imports
        github.com/sirupsen/logrus tested by
        github.com/sirupsen/logrus.test imports
        github.com/stretchr/testify/assert loaded from github.com/stretchr/testify@v1.3.0,
        but go 1.16 would select v1.6.1
~~~

**Comment by 89z** [comment]
You can repro by starting a new module with this file:

~~~go
package one

import (
   _ "github.com/89z/mech"
   _ "github.com/walles/moar"
)
~~~

**Comment by 89z** [comment]
workaround:

~~~sh
go mod tidy '-compat=1.17'
~~~

**Comment by walles** [comment]
Not sure what to do here.

I just tried to repro and failed.

Just like you, I don't know what that error message means either.

And `logrus` is used to provide a `--debug` flag for more verbose logging (#20) so I don't want to drop `logrus`...

**Comment by 89z** [comment]
I think its because my `go.mod` is 1.17:

https://github.com/89z/mech/blob/master/go.mod

but I dont think that should be a problem - I think maybe the other packages need to update. Anyway, whatever you decide is fine

**Comment by walles** [comment]
I will do nothing then.

If you change your mind and decide you actually do want something fixed in `moar`, feel free to reopen this ticket!

**Comment by 89z** [comment]
You could change your `go.mod` to 1.17:

https://github.com/walles/moar/blob/a710033d6fc558d6129befe57ba0e7a6d5bc8a15/go.mod#L1-L3

and push a new tag. Not sure if that will fix it, but if you want to try it, I can test to see if it works - up to you

**Comment by walles** [comment]
I'm a bit wary of bumping that, if somebody has an older package where they want to use `moar` it's better for them if I remain at `1.16`.

Maybe this rationale is very hypothetical though...

**Comment by 89z** [comment]
well if you decide to do it, let me know. Not a big deal either way. Thanks!
