### ISSUE TITLE
Windows binary?

### ISSUE THREAD

**Issue by tgice** [walles/moar#70]
Hi, I'm interested in using moar but it appears there are no Windows binaries available.  Do you have any plans to build for Windows?

**Comment by walles** [comment]
New release with a Windows binary: <https://github.com/walles/moar/releases/tag/v1.8.2>

Can I please ask you to try this binary and report back here?

I'm just cross compiling and everything looks fine, but if you could *run* the binary and tell me how it went that would be super!

**Comment by tgice** [comment]
Woohoo! It works:

![image](https://user-images.githubusercontent.com/11559535/132865060-28bf1ec9-c8f1-49a4-a16b-ca2b6b73abaa.png)

I've not extensively tested it yet, but I'll continue to experiment with it.  Thanks so much for your quick response.  Cross compiling languages are great, eh?

**Comment by walles** [comment]
Thanks for verifying @tgice!
