### ISSUE TITLE
Bump alecthomas/chroma

### ISSUE THREAD

**Issue by 89z** [walles/moar#74]
I had a pull request merged recently:

~~~
github.com/alecthomas/chroma/pull/555
~~~

which is available starting with `alecthomas/chroma` version 0.9.3 (Sep 2021). Can you please bump the Chroma version?

https://github.com/walles/moar/blob/77f4b0aebe1aff0ef6f63a445e8bbfdd9a1909bb/go.mod#L5-L6

This will help to remove this old package from the requirements:

https://github.com/walles/moar/blob/77f4b0aebe1aff0ef6f63a445e8bbfdd9a1909bb/go.sum#L10-L11

**Comment by walles** [comment]
@89z would you like me to do a new release as well?

**Comment by 89z** [comment]
Thank you sir!
