### ISSUE TITLE
Error Warning on Moar running on macOS 12.2

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#79]
Hi Walles

I got this message on console while reading and closing the log

Please post the following report at <https://github.com/walles/moar/issues>,
or e-mail it to johan.walles@gmail.com.

Version: v1.8.4
LANG   : en_US.UTF-8
TERM   : screen-256color

GOOS    : darwin
GOARCH  : amd64
Compiler: gc
NumCPU  : 12

time="2022-02-10T23:48:56.218109+05:30" level=warning msg="Got invalid UTF-8 sequence on ttyin: \x1b[<65;132;22M\x1b[<65;132;22M\x1b[Ma\xa46\x1b[Ma\xa46"

**Comment by walles** [comment]
Is this something you can reproduce? If so, how?

Does it happen a lot? Just once?

I *think* this is related to something you do with your mouse.

What I know is that these are actually four events:
```
\x1b[<65;132;22M
\x1b[<65;132;22M
\x1b[Ma\xa46
\x1b[Ma\xa46
```

`\x1b[` is called "CSI" and marks the start of each sequence.

The two first ones are wheel-up events.

The two last ones are both `\x1b[Ma\xa46`, and these I don't know.

`\x1b[M` is related to mouse control at least: <https://www.xfree86.org/current/ctlseqs.html#Mouse%20Tracking>

Then we get `a`, `\xa4` and `6`, which I still haven't figured out what they mean.

**Comment by ciscohack** [comment]
i was reading a log and saw this issue and i saw only once .. infact i am out so not able to test it further

**Comment by walles** [comment]
Help wanted!

Either of these would be super helpful:
* Explain to me what the escape sequences we're getting actually mean
* Tell me how to repro this

**Comment by walles** [comment]
I'll never be able to do anything with this, closing.

If somebody can explain what the escape sequences mean, please re-open this ticket!
