### ISSUE TITLE
Hide bottom bar to better replicate less?

### ISSUE THREAD

**Issue by GNOMES** [walles/moar#81]
Is there a flag to hide the bottom bar to act more like less?

**Comment by walles** [comment]
I find the bottom bar provides useful information, without taking up almost any screen real estate.

In what situation do you think `moar` would be better off without the bottom bar?

**Comment by GNOMES** [comment]
Personally the white line is a bit bright on a black background. 

I could see a toggle to disable it outright, or a flag to invert the colors so it matches less.

**Comment by GNOMES** [comment]
That's great, and positions moar as more of a "less + colors drop in replacement".

**Comment by walles** [comment]
If inverted is too bright...

> Personally the white line is a bit bright on a black background.

... but then regarding `less`' inverted text...

> That's great

... is inverted text all right or is it too bright?

Or is it that your terminal color settings are different from mine? If you could **post a screenshot of *your* terminal window** with `moar` running that would be super!

Also, here's `less` again but I pressed `=`. Which do you like best, this one (which is what I used as inspiration for the `moar` status line) or the previous one I posted?

<img width="612" alt="less-bashrc-=" src="https://user-images.githubusercontent.com/158201/154620146-0cfdcbfd-ea31-4768-b60b-7ec6b0ab55c7.png">

**Comment by GNOMES** [comment]
I am not against having a status line. This is `less` on my box after hitting the = button.

![Screen Shot 2022-02-18 at 10 29 03](https://user-images.githubusercontent.com/7462046/154723204-580ed0a7-c522-4186-a79b-bfd5fe46f281.png)
 
 The big complaint was against the white bar with black text spanning terminal window. 
 
 
 I would be happy with any of the three options:
 
1.  Feature flag to hide bar ( original question ).

2. Flag to allow white text on black background ( My new preferred choice after I realized that Less always has had a status bar. The white bar in Moar made it jump out to me. The Less color scheme blended in... )

3. Flag for the "minimal" bar in your screenshot. It's less "bright", and it gives a Less w/o = button appearance. 

Regardless of your decision on the matter, I would think a feature flag would be best so people have choice.

**Comment by walles** [comment]
Made an 1.8.5 release supporting three status bar flavors (see below).

Binaries available on the release page, homebrew in progress: https://github.com/Homebrew/homebrew-core/pull/95396

<img width="570" alt="Skärmavbild 2022-02-18 kl  19 23 31" src="https://user-images.githubusercontent.com/158201/154740830-3c490ca8-9c99-4334-ac6f-532d27a51052.png">
<img width="570" alt="Skärmavbild 2022-02-18 kl  19 23 45" src="https://user-images.githubusercontent.com/158201/154740838-9eb0d12a-12a4-493b-9b89-00c86526a01b.png">
<img width="570" alt="Skärmavbild 2022-02-18 kl  19 23 19" src="https://user-images.githubusercontent.com/158201/154740826-9c983c89-753c-4c19-bedb-d7fd5c4ff961.png">
