### ISSUE TITLE
Visual Bug for some digits

### ISSUE THREAD

**Issue by chrisgrieser** [walles/moar#83]
Thanks for this pager – I looked ages for an alternative to less...

I noticed some weird visual bug where a red question mark is printed in moar. I tried `man pwd`
<img width="1101" alt="Screenshot 2022-02-23 14 42 29" src="https://user-images.githubusercontent.com/73286100/155332624-97548d28-0110-452c-bac9-8af7fcad7502.png">

The same in less:
<img width="1069" alt="Screenshot 2022-02-23 14 42 50" src="https://user-images.githubusercontent.com/73286100/155332763-7212c49f-4169-4ea8-b673-346614dffb59.png">

The colorizing (less_termcap) doesn't seem to be the cause of this, turning of all coloring still creates those questions marks
<img width="1033" alt="Screenshot 2022-02-23 14 49 42" src="https://user-images.githubusercontent.com/73286100/155332894-31a49df1-9b08-438d-911c-9c903e9da07c.png">

Unfortunately, I cannot really pin down when the bug occurs. it seems to be related to digits, but does not affect all digits 🤔

**Comment by chrisgrieser** [comment]
> Do you have any kind of sources for what the man page looks like?
Do you mean the man page source? Not sure how to get those for the pre-installed commands like `pwd`, but since the same problem also occurs for manually installed CLIs, I tried out a few of them.

And indeed, the man page for `fasd` looks especially bad 
<img width="1059" alt="Screenshot 2022-02-23 23 24 24" src="https://user-images.githubusercontent.com/73286100/155419801-9f781f69-4654-4969-9452-756448ffcb84.png">

looking through the repo, it looks like the man page is created from this file: https://github.com/clvv/fasd/blob/master/fasd.1

**Comment by walles** [comment]
Are you on an UTF-8 locale? What does `locale` tell you?

Here's mine:

```
~ $ locale
LANG="sv_SE.UTF-8"
LC_COLLATE="sv_SE.UTF-8"
LC_CTYPE="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_ALL=
~ $
```

**Comment by chrisgrieser** [comment]
yep, everything utf-8 here.
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by walles** [comment]
I'm unsure what to do with this on the `moar` side.

Do you have any suggestions for changes to `moar` that would make it better for you in this case?

I kind of like highlighting invalid UTF-8, but in this case it's just annoying.

**Comment by chrisgrieser** [comment]
Thanks!

**Comment by walles** [comment]
Try this:
```bash
export MOAR='--render-unprintable=whitespace'
```

See `moar --help` for what else you can set it to.

Docs added, thanks for pointing out they were missing!
https://github.com/walles/moar#configuring
