### ISSUE TITLE
Moar search freeze in  iterm2 with syntax highlight trigger enabled

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#84]
Hello Expert,

Moar performance in iterm2 with trigger enable seems degraded. today while searching in very big file and wrap disabled i noticed if i run search inside the moar pager it gets freezed but if i turn on wrap then performance is better.

**Comment by ciscohack** [comment]
I can attach my iterm2 config which you can load and open huge log file add multiple places dtls and tls keyword and search it you will see the issue.. why these 2 keyword i mentioned becoz i have enabled a color highlight for this 
[com.googlecode.iterm2.plist.zip](https://github.com/walles/moar/files/8235487/com.googlecode.iterm2.plist.zip)

**Comment by ciscohack** [comment]
Seems i have fixed the issue by modifying some dynamic profile config of iterm2.. will monitor and update in case need help. thanks

**Comment by ciscohack** [comment]
Okay so moar has some serious problem while search and syntax highlight enabled sometime it's getting freezed

**Comment by walles** [comment]
Can you reproduce these issues in the macOS default Terminal program?

**Comment by walles** [comment]
Also @ciscohack, are you running Chromaterm when you see these problems? Does this repro without Chromaterm?

**Comment by ciscohack** [comment]
@ciscohack Please close the ticket ..not used moar quite sometime. will reopen if needed thanks a lot brother

**Comment by walles** [comment]
Closing as requested by reporter.
