### ISSUE TITLE
--dumb is not recognised option

### ISSUE THREAD

**Issue by michal-piekarski** [walles/moar#85]
Calling `moar --dumb` causes:
`flag provided but not defined: -dumb`

**Comment by walles** [comment]
Dumb question maybe (pun intended), but what do you expect when passing `--dumb`?

**Comment by michal-piekarski** [comment]
I assumed that I should submit this in line with readme:

> The intention is that Moar should work as a drop-in replacement for [Less](http://www.greenwoodsoftware.com/less/). If you find that Moar doesn't work that way, [please report it](https://github.com/walles/moar/issues)!

I think this means that if I replace `less --dumb` with `moar --dumb` it should have the same effect.
This is not the case, `moar --dumb` returns an error about undefined option.

Description of the `--dumb` option for `less` is:
```
       -d or --dumb
              The -d option suppresses the error message normally
              displayed if the terminal is dumb; that is, lacks some
              important capability, such as the ability to clear the
              screen or scroll backward.  The -d option does not
              otherwise change the behavior of less on a dumb terminal.
```

I don't expect 100% the same functionality but at least the option should be recognized - even if it does nothing.

**Comment by walles** [comment]
Thanks for the clarification @michal-piekarski!

My intent was never to support every option in `less`, but rather have a nice pager that is obvious to use if you're coming from `less`.

I changed the phrasing you're referring to to try to convey this better. In retrospect I think the previous phrasing could totally be interpreted the way you did.

For now I'm weakly against adding flags just to ignore them. If lots of people show up asking for this I might reconsider.
