### ISSUE TITLE
[Feature Request] `man` page

### ISSUE THREAD

**Issue by hiddeninthesand** [walles/moar#87]
It would be nice to have a manpage for moar

**Comment by walles** [comment]
Nice to have yes, but it would also require writing and maintaining it.

Docs are already maintained (to the best of my ability...) in `moar --help` output and in the `README.md`, this would add a third place.

What's the concrete use case here @hiddeninthesand , when do you think a man page would provide additional value to what's already in `--help` and in the `README.md`?

**Comment by hiddeninthesand** [comment]
> What's the concrete use case here @hiddeninthesand , when do you think a man page would provide additional value to what's already in `--help` and in the `README.md`?

In short, standardization. The README would only be useful to those who are looking at the repository itself, and not useful to most end users, and while the CLI help flag is always appreciated, it does seem overly brief compared to the manpage of `less`, which takes heavy advantage of the built in pager of the manual. 

I believe ideally most of the contents of the README should be in the manpage for easy offline viewing, while the help page could be the brief version of what's held in the manual.

**Comment by nkh** [comment]
I second the man page request, and it's now possible to generate it from markdown.

**Comment by walles** [comment]
@nkh do you have an example command line to convert moar's `README.md` into a usable man page?

**Comment by nkh** [comment]
https://github.com/search?q=markdown+man+page

I'm playing with this one right now https://kristaps.bsd.lv/lowdown/ it also has a github page https://github.com/kristapsdz/lowdown

but you'll need more than just convert the moar's README, man pages have a format that should be followed. here's an example https://github.com/nkh/vimkat. There are plenty resources.

https://linux.die.net/man/7/man-pages
https://itsfoss.com/linux-man-page-guide/

a few man pages that are worth looking at: bash, tmux, perlrun, ...

**Comment by walles** [comment]
Homebrew progress: https://github.com/Homebrew/homebrew-core/pull/106321

**Comment by walles** [comment]
Done.

**Comment by nkh** [comment]
Options should be in the man page, that's what the man page is for

**Comment by nkh** [comment]
long options should have double dash ... --some-option, even if one accept them on the command line as you do. and that makes it easy to know which one are short and which one are long
