### ISSUE TITLE
[Bug] Moar suggests setting wrong path as the environment variable for becoming the default pager

### ISSUE THREAD

**Issue by hiddeninthesand** [walles/moar#88]
When running `moar --help`, Moar will suggest that you add it to your `.bashrc` file as your default pager, alongside the line required, for example: 

```
To make Moar your default pager, put the following line in
your .bashrc or .bash_profile and it will be default in all
new terminal windows:
   export PAGER=/path/to/binary
   ```

This (potentially) incorrectly assumes that the `moar` application file is in your current working directory, which can lead to recommending the user the wrong line to insert into their `.bashrc` file.

**Comment by walles** [comment]
Which version of `moar` is this (`moar --version`)?

When I try the same thing with `v1.9.1` I get:
```
To make Moar your default pager, put the following line in
your .bashrc or .bash_profile and it will be default in all
new terminal windows:
   export PAGER=/Users/johan/src/moar/moar
```

**Comment by walles** [comment]
You are right, thanks for reporting!

I will look into this and make sure it's done properly.

**Comment by hiddeninthesand** [comment]
Appreciate it!

**Comment by walles** [comment]
Made a new release for it, Homebrew status here: <https://github.com/Homebrew/homebrew-core/pull/99564>

**Comment by hiddeninthesand** [comment]
Looks good, already pushed it to the [MPR.](https://mpr.makedeb.org/packages/moar)
