### ISSUE TITLE
Missing navigation mappings

### ISSUE THREAD

**Issue by mgrubb** [walles/moar#90]
The <count>g and <count>G  do not work, in less they will take you to line <count>.
While u and d work, CTRL-u, and CTRL-d (the same functionality) do not.  While not a huge issue, the CTRL versions are ingrained in muscle memory after 25+ years.

These were some compatibility issues that immediately caught me up.

**Comment by walles** [comment]
Done in `v1.9.3`: https://github.com/walles/moar/releases/tag/v1.9.3

Should show up in Homebrew shortly: https://github.com/Homebrew/homebrew-core/pull/100597

Thanks for reporting Michael!
