### ISSUE TITLE
[Feature Request]  option to set the continuation glyph

### ISSUE THREAD

**Issue by nkh** [walles/moar#94]
reversed ">" pokes holes in the eye of the beholder

and option to give a continuation string (Eg: "some_ansi_color+...") would be great

**Comment by walles** [comment]
Maybe it should simply be replaced entirely.

What would be your suggestion?

**Comment by walles** [comment]
And another question, do you think the go-left and the go-right continuation markers should be the same?

Right now they are `<` and `>` in inverse video (as you noticed).

Should `<` and `>` maybe be highlighted in two separate styles?

**Comment by nkh** [comment]
I think that an option is the way to go, you keep to chose the default and "fuzzy" users like me get to chose what they want and in the color they want.

You have a good point with the left/right glyphs, should they be the same,different? the solution would be to give 2 options.

it os slightly more work for you, you need to take the length of the user's string into account (counting the ANSI escape codes, except if you have separate options for the string and the color), but I believe that some of us spend time tweaking their display so it's comfortable to work in for hours.

**Comment by walles** [comment]
But what do you think you'd like as a "more contents to the right" indicator?

**Comment by nkh** [comment]
I think the indicator (right or left) is a good thing I just want to be able to chose the indicator (I like ellipsis, specially unicode, but one character would be fine) and chose the color so it doesn't poke holes in my eyes at 02:00 hen everything is dark.

**Comment by walles** [comment]
1. Do you have an example file you could attach here where you find the current marker annoying?
1. Also, when viewing this file, how many characters wide is your terminal window?

**Comment by nkh** [comment]
there was a screenshot here where you can see the markers https://github.com/walles/moar/issues/93

my viewing width varies, my "normal" width is 190 but I use/would use moar in an extra terminal pane via my file manager and the width varies; here's a screenshot  when width is minimum

![screenshot_2022-07-21_09-17-38](https://user-images.githubusercontent.com/45409/180153720-4f15583d-c6bf-4b0a-974e-ee4ab12e7235.png)
