### ISSUE TITLE
Unrecognized ANSI code

### ISSUE THREAD

**Issue by nkh** [walles/moar#95]
time="2022-07-20T09:57:56.386401977+02:00" level=warning msg="Unrecognized ANSI SGR code <101>"

This is of course an extreme case but that's actually a real case I have (I'm generating the file so i will also work on it on my side)

the code will also be displayed
![screenshot_2022-07-20_10-02-41](https://user-images.githubusercontent.com/45409/179929898-76d7f91c-c471-43a6-9e9e-bae15a2ceb3c.png)

less will groak it:
![screenshot_2022-07-20_10-03-06](https://user-images.githubusercontent.com/45409/179929967-d95b0a9d-fc83-42f1-a7f8-610aff48a120.png)

**Comment by walles** [comment]
Could you attach the file? I'd like to have a look at it.
