### ISSUE TITLE
moar doesn't recognize type of file without extension

### ISSUE THREAD

**Issue by nkh** [walles/moar#96]
bash files don't get colorized if they don't have a sh extension, which bash files seldom have

I understand that you want to put together paging and colorizing but maybe those should be kept separate or at least controllable with some option

not really a problem for me, I use moar in a controlled fashion not as my main $PAGER.

**Comment by walles** [comment]
Not sure what the ask is here, could you give an example of what would make you consider this issue fixed? Content based file type guessing like `file`?

**Comment by walles** [comment]
> Note that won't use moar for that

* This would be some work
* This would be easy to get wrong
* Not sure how many people would be helped even if I did implement this

I think I'll postpone this until there's a clearer ask.

If you think this is the wrong decision, feel free to reopen / question me here!
