### ISSUE TITLE
Automatic decompression of compressed files

### ISSUE THREAD

**Issue by nkh** [walles/moar#97]
IMHO, if the compressed file contains multiple files a listing should be displayed not binary data. the same goes for content that is a single file, if it is not a text file, which might include ANSI code, it should not be displayed at least without asking the user, there are better ways to look at binary, maybe a hex dump would be more useful.

**Comment by walles** [comment]
What kind of archives would you like to view with `moar`?

**Comment by walles** [comment]
> I look at compressed files i my own viewer

* There are lots of zip-like file formats out there
* I'm not sure anybody would use this even if I implemented this

I think I'll postpone this until there's a clearer ask.

Feel free to reopen / question this if you feel I'm taking the wrong decision here!

**Comment by nkh** [comment]
I must have misunderstood the documentation : Automatic decompression of compressed files (.gz, .bz2, .xz)

I thought that was already implemented!

**Comment by walles** [comment]
This works, and will show the same thing as `moar /etc/passwd`:

```
gzip --stdout < /etc/passwd > passwd.gz
moar passwd.gz
```

IIUC your expectation is that if I `moar something.tar.gz`, `moar` should:
1. Decompress the file (as it currently does)
2. Figure out that the uncompressed contents is really an archive, and list the archive's contents

2 is not implemented.

Do you think this should be clarified in the README?

**Comment by nkh** [comment]
2 is what expected; I guess other will so it may be a good idea to clarify in the docs

**Comment by walles** [comment]
That clarifies things, reopening!

**Comment by walles** [comment]
@nkh do you think this new phrasing is better?

**New**

> - **Automatic decompression** when viewing [compressed text files](https://github.com/walles/moar/issues/97#issuecomment-1191415680) (`.gz`, `.bz2`, `.xz`)

**Old**

> - **Automatic decompression** of compressed files (`.gz`, `.bz2`, `.xz`)
